### ISSUE TITLE
Economy problem

### ISSUE THREAD

**Issue by XSilverSlayerX** [drtshock/PlayerVaults#103]
When opening Player Vaults first time it charges 2000g like its suppose to but every time someone opens the same vault it keeps charging them, Its only suppose to charge them for creating it but it charges it for opening it even though open is set to 0g. help...
Config:
  cost-to-create: 2000 <--- charges first time to create like normal.
  cost-to-open: 0 <--- charges 2000 even though its zero
  refund-on-delete: 500

**Comment by XSilverSlayerX** [comment]
Also I have reset EVERYTHING and it still does not work. Tried it a thousand different ways. #Help

**Comment by drtshock** [comment]
Which versions of playervaults, vault and spigot?

**Comment by XSilverSlayerX** [comment]
Vault 1.5.3
PlayerVault 3.5.6
Spigot 1.8.8

**Comment by XSilverSlayerX** [comment]
All latest versions.

**Comment by drtshock** [comment]
Looks like a silly mistake. Build 183 should fix it https://ci.drtshock.net/job/PlayerVaults/183/, please confirm once you've tested :)

**Comment by XSilverSlayerX** [comment]
It worked Thanks!

**Comment by drtshock** [comment]
\o/ ;D
