### ISSUE TITLE
Per-Vault Permissions

### ISSUE THREAD

**Issue by SolarShrieking** [drtshock/PlayerVaults#105]
Hey,
I was wondering if you could include a way to add per-vault permissions. The way I imagine it is the player has access to specific vaults defined in the permissions, more than just playervaults.amount.#, so like they can access Vault 1, 10, and 20, but not Vaults 2-9, 11-19, and 20+. Something like playervaults.usevault.#.

Thanks for your time :)

**Comment by drtshock** [comment]
why though?

**Comment by SolarShrieking** [comment]
We have a Ladder Permissions system, and we want each rank to have a vault. Some players will be in various places on each rank ladder, so just using amount wouldn't be very viable.
Below, a user would be Ladder 1, Rank 2, and Ladder 2, Rank 4, so they would ideally have access to Vaults 1, 2, 6, 7, 8, 9. When they got to the top of each ladder, they would have access to Vaults 1-10.

I recognize that this is kind of a weird request, but I hope you can implement it.

Ladder 1
>Rank 1
>>Vault 1
>Rank 2
>>Vault 2
>Rank 3
>>Vault 3
>Rank 4
>>Vault 4
>Rank 5
>>Vault 5

Ladder 2
>Rank 1
>>Vault 6
>Rank 2
>>Vault 7
>Rank 3
>>Vault 8
>Rank 4
>>Vault 9
>Rank 5
>>Vault 10

**Comment by drtshock** [comment]
sorry but no
