### ISSUE TITLE
'Vault Does Not Exist' Issue

### ISSUE THREAD

**Issue by TehMynx** [drtshock/PlayerVaults#108]
I'm sorry if this has already been answered else where, But I have realised that only I (I have star perms) can access Playervaults. All others who have the permission nodes seem to get the message 'Vault does not exist' and players without get the 'Error: You have not got permission to open that'
Here is the Group:

  Legend:
    inheritance:
    - Player
    options:
      prefix: '&8[&5Legend&8]'
    permissions:
    - essentials.nick
    - essentials.near
    - essentials.feed.others
    - essentials.tptoggle
    - essentials.keepxp
    - essentials.back
    - essentials.feed
    - essentials.condense
    - essentials.clear
    - essentials.hat
    - essentials.recipe
    - essentials.kit.brewing
    - essentials.kit.raid
    - essentials.kit.legend
    - playervaults.workbench
    - playervaults.signs.use
    - playervaults.size.6
    - playervaults.amount.1
    - -playervaults.commands.use
    - essentials.kit.monthly
    - essentials.sethome.multiple.legend
    - essentials.ptime
    - silkspawners.silkdrop.*
    - essentials.pweather

**Comment by drtshock** [comment]
Because you're negating playervault commands? ;o What sign are they using to open them

**Comment by TehMynx** [comment]
I did /pvsign 1 and right clicked the allocated sign. I have negated the commands so it's signs only due to the obvious issue of running away and storing items in a pvp battle or something along the lines of that. I can open it with the sign but they can't. When they try they get the message "This vault does not exist"

**Comment by TehMynx** [comment]
Any news on this?
