### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by TheExceed** [drtshock/PlayerVaults#113]
I opened a similar issue awhile ago where the players can dupe items upon restart or stopping the server.
Method:
Open your vault, put in any item, close the vault
Open your vault, remove the items in vault to your inventory. DO NOT CLOSE VAULT.
Restart server.

You will have the items in your inventory and your vault. I have tested it. I can make a video if you would like. I have used both /restart, /stop and the restart and stop buttons for multicraft console panel.
Works for both.

**Comment by drtshock** [comment]
I'm unable to reproduce this. It closes all online player's vaults on shutdown if they have it open so there wouldn't be a way to do this unless you server doesn't shut down properly.

**Comment by TheExceed** [comment]
Would a single plugin that has a GUI cause this problem? If that plugin doesn't have a close GUI on shutdown event?

**Comment by drtshock** [comment]
no since we close all playervaults inventories on shut down.
https://github.com/drtshock/PlayerVaults/blob/master/src/main/java/com/drtshock/playervaults/PlayerVaults.java#L119

**Comment by TheExceed** [comment]
Then I do not what would cause the server to shut down incorrectly, if I sent you the log file, would you be able to tell?

**Comment by drtshock** [comment]
Perhaps. Let me add a debug message there to show who it closes for as well.

**Comment by drtshock** [comment]
Try build 184.
https://ci.drtshock.net/job/PlayerVaults/

Enabled debug in the config then send me the full latest.log in a pastebin please.

**Comment by TheExceed** [comment]
https://www.dropbox.com/s/eigqvckd6wufnho/latest.log?dl=0

**Comment by drtshock** [comment]
Can you reproduce the bug with that build with debug mode enabled*

**Comment by TheExceed** [comment]
Yes, I did it in the latest.log as well.

**Comment by TheExceed** [comment]
Here is another: https://www.dropbox.com/s/ara55dpy0af6bkh/latest%20%282%29.log?dl=0

**Comment by TheExceed** [comment]
Here is a video of it occuring. 
https://www.dropbox.com/s/3jpeiwtim43kxox/Dupe%20Glich.mp4?dl=0

**Comment by drtshock** [comment]
Can you paste the full log of it, including shutdown?

**Comment by TheExceed** [comment]
Both should have shut down, no?

**Comment by TheExceed** [comment]
http://pastebin.com/3BX3fJD4

**Comment by TheExceed** [comment]
Any idea?

**Comment by drtshock** [comment]
Try to reproduce this with build 185 https://ci.drtshock.net/job/PlayerVaults/185/

**Comment by drtshock** [comment]
Nevermind, build 186.

**Comment by drtshock** [comment]
All joking aside, use https://ci.drtshock.net/job/PlayerVaults/187/

**Comment by TheExceed** [comment]
Lmao, you sure I dont wanna use 188 or 189?

**Comment by TheExceed** [comment]
But, yes it is fixed. Thanks
