### ISSUE TITLE
Could not pass event InventoryClickEvent to PlayerVaults

### ISSUE THREAD

**Issue by souleaters22** [drtshock/PlayerVaults#114]
Every time i log onto the consol I see a bunch off errors with this 

https://gyazo.com/44d5246b61ec60085cb9d3cd68c7a354

Anyone know what i can do to fix this?

**Comment by drtshock** [comment]
Try using spigot.

**Comment by souleaters22** [comment]
The server is currently running spigot 1.8.7

**Comment by blok601** [comment]
I am getting the same error.

**Comment by drtshock** [comment]
So paste the error.

**Comment by johnc291992** [comment]
looks like PlayerVaults is version/bukkit/spigot dependent...  may as well save everything in NBT so that everything is properly serialized...?

**Comment by drtshock** [comment]
It's not version dependent.
