### ISSUE TITLE
Playervaults inventoryCloseEvent (PerWorldPlugins?)

### ISSUE THREAD

**Issue by agentroop** [drtshock/PlayerVaults#115]
Here's the log of an error I've been experiencing. It has resulted in the deletion of many player's vault data. As you can see, the error does mention a different plugin I am using but it clearly says "**** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****"

I'm running Spigot 1.8.7 on a multiverse server.

Error: http://pastebin.com/egtpTKjs

Thanks in advance for any help. In the meantime I'm going to have to stop running the plugin.

**Comment by drtshock** [comment]
It means your plugin didn't enable correctly.
