### ISSUE TITLE
Possible dupe glitch due to players able to open multiple vaults at once

### ISSUE THREAD

**Issue by ijskobar** [drtshock/PlayerVaults#116]
The inVault map is populated with the player's uuid but is queried by the player's name on some occasions, thus the parts of the code which rely on inVault aren't working as they should.

For example,

Insert
https://github.com/drtshock/PlayerVaults/blob/master/src/main/java/com/drtshock/playervaults/commands/VaultCommand.java#L35

Query:
https://github.com/drtshock/PlayerVaults/blob/master/src/main/java/com/drtshock/playervaults/commands/VaultCommand.java#L27

**Comment by drtshock** [comment]
Thanks for pointing this out.
