### ISSUE TITLE
How do I allow PV access in only one world ?

### ISSUE THREAD

**Issue by 151baccardi** [drtshock/PlayerVaults#117]
I am using Spigot 1.8.7 and playervault 3.5.7 and essentials groupmanager. I would like to add a donator feature for players to use player vaults. However, when the permission is added to their users file they now have access to pv in all worlds. Could you add a section in the config that has enabled worlds: -- Or how do I approach this ? Our server has 20 worlds and I copy the users.yml file from groupmanagers main world to all the other worlds manually... What am I missing or is there a way to override a users permission in the groups permission file ??

**Comment by drtshock** [comment]
Only add the permission in the worlds that you want them to have access to it.
