### ISSUE TITLE
Player Vaults changes Leather Armor

### ISSUE THREAD

**Issue by Quintoking** [drtshock/PlayerVaults#118]
Player Vaults changes Leather Armor from enchanted named and colored to regular. Changes nothing else? What can I do to fix this. No errors in con, only this problem.

**Comment by drtshock** [comment]
Which spigot version, which playervaults version, and what specific data? Is it something that you can naturally get in game?

**Comment by Quintoking** [comment]
Ok so i figured out if we hide enchants it will i guess bug it out thinking there is no enchants for soem reason? my server is a cracked 1.8.7 bukkit with the most updated playervaults and Mythic mob plugin. When we use mythic mobs to create item we have the choice to hide enchants but still enchanted. The problem consist when put into a playervualt shut playervault and open it again it goes back to normal leather armor.

**Comment by drtshock** [comment]
So don't create it with hidden enchants

**Comment by Quintoking** [comment]
Yea... like i said i figured it out.. was just letting you know man sorry..
