### ISSUE TITLE
Players having extra space then they should be having.

### ISSUE THREAD

**Issue by 50ouncebrew** [drtshock/PlayerVaults#119]
Hey, im having a problem with playervaults so i reset my server map so i deleted uuid vaults folder too and now my low donator ranks which are supposed to get 9 slots are getting a whole dub slot from pv now i tried deleteing it but it comes back up with a whole dub

And its only happening to a few players that i reset buycraft commands to but i didnt add a command on  buycraft to give the perm.

**Comment by drtshock** [comment]
You sure the vaults aren't leftover from before or they don't have permission for a bigger one?

**Comment by 50ouncebrew** [comment]
The isssue was fixed randomly not sure what happened, but they returned back to normal after a day.
