### ISSUE TITLE
site may be experiencing temporary downtime?

### ISSUE THREAD

**Issue by augesrob** [drtshock/PlayerVaults#120]
28.09 09:12:31 [Server] WARN at java.lang.Thread.run(Thread.java:745)
28.09 09:12:31 [Server] WARN at com.drtshock.playervaults.util.Updater$UpdateRunnable.run(Updater.java:513)
28.09 09:12:31 [Server] WARN at com.drtshock.playervaults.util.Updater.access$200(Updater.java:35)
28.09 09:12:31 [Server] WARN at com.drtshock.playervaults.util.Updater.read(Updater.java:474)
28.09 09:12:31 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
28.09 09:12:31 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
28.09 09:12:31 [Server] WARN java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.curseforge.com/servermods/files?projectIds=50123
28.09 09:12:31 [Server] WARN If you have not recently modified your configuration and this is the first time you are seeing this message, the site may be experiencing temporary downtime.

Running on spigot-1.8.8-R0.1-SNAPSHOT.jar

**Comment by drtshock** [comment]
Perhaps. Just disable the check for the time being. Though it might be wise for us to catch that.
