### ISSUE TITLE
Permission help!

### ISSUE THREAD

**Issue by Ry3guy2002** [drtshock/PlayerVaults#121]
When i added the permissions

playervaults.amount.3: true
playervaults.commands.use: true

and a default player does /pv 1 it said you don't have permissions for that!

PLS HELP

**Comment by KevinLimbach** [comment]
I've been having the same issue except only with the following permissions:
 Colonist:
    default: false
    permissions:
    - playervaults.size.1
    - playervaults.ammount.1
    - playervaults.commands.use
    - essentials.hat
    - essentials.workbench
    inheritance:
    - peasant
    info:
      build: false
      prefix: '&f&l[&2Colonist&f&l]&f '
      suffix: ''
I added three commands and none have seemed to work! Please fix!

**Comment by drtshock** [comment]
@KevinLimbach it's amount, not ammount

@Ry3guy2002 then you must be doing something else wrong, like not giving people the right group.

**Comment by Ry3guy2002** [comment]
I am not giving people groups im putting the permissions in the permission file.
