### ISSUE TITLE
Personal vault syncs with other players

### ISSUE THREAD

**Issue by skyewolfe** [drtshock/PlayerVaults#123]
An issue that has been happening with my staff is that our player vaults will seem to sync up with random players. If we remove items from it, they stay in the players personal vault still. It's only the /pv 1 that does it

**Comment by drtshock** [comment]
Which version are you on? This was an issue awhile ago but isn't anymore.

**Comment by skyewolfe** [comment]
We're running version 3.5.1

**Comment by drtshock** [comment]
Update https://github.com/drtshock/PlayerVaults/blob/master/pom.xml#L7
