### ISSUE TITLE
Problems with custom item data

### ISSUE THREAD

**Issue by maxlehot1234** [drtshock/PlayerVaults#124]
Hi, could you look into this pelase?
https://www.spigotmc.org/threads/minebomb-paid.83931/page-5#post-1076756

Save items date like a dev explain it here:
https://www.spigotmc.org/threads/minebomb-paid.83931/page-5#post-1076776

I try to put minebombs into the playervault and inside the ./pv all data will be removed from the bombs so the bombs doesn't work anymore... Please check this and fix this, because all pof ym players have this bug and I think a lot of servers owners simply stop to used your plugin caused of this bug...

Thank you

**Comment by drtshock** [comment]
They should use something like lore to display / save the info they need if they expect it to save. And please describe further issues directly in the ticket instead of just linking.

**Comment by maxlehot1234** [comment]
I explain all in the tickets, read it better:
I try to put minebombs into the playervault and inside the ./pv all data/lore will be removed from the bombs so the bombs doesn't work anymore caused of this...

I just link the dev answer:
https://www.spigotmc.org/threads/minebomb-paid.83931/page-5#post-1076776

This is what the minebomb dev say:
it sounds like the plugin does not handle ItemStack properly.... probably failing to do proper copy or data saving.... whoever wrote your player vaults should save the data properly....

If you code properly (like vkbackpack, which can be used as player vault), you won't lose those critical information of Items.

since I did not write your player vault nor have access to the code, you need to ask the developer of your player vault to fix it and save all the information associated with an item.



Is it good now?

**Comment by drtshock** [comment]
I'm not going to use NMS to save data.
