### ISSUE TITLE
Letterheads plugin incompatibility

### ISSUE THREAD

**Issue by Azfaloth** [drtshock/PlayerVaults#127]
Hello! I've been having an issue with playervaults in relation to the letterheads plugin.
Link is here https://www.spigotmc.org/resources/letterheads.14685/
This plugin generates heads with custom skins (as letters) to be used in builds etc.
This plugin supposedly uses NBT data to skin the heads as required.

The error I have is when a letterhead is placed in a vault. The console shows this

http://pastebin.com/hTBHuCsz

After this error, if I open any chest and then open that particular playervault, all the contents of the chest are written into the player vault and its original contents are wiped.

Is a fix possible for this? Thank you for your time and your plugin.

**Comment by drtshock** [comment]
Because it's not setting an owner of the skull, it's setting other stuff that it shouldn't be. You should bring this up with the author of that plugin.

**Comment by Azfaloth** [comment]
That may be so. I have contacted the author of that plugin about this before I contacted you. And I have contacted them again and hopefully they will fix this issue.

But I also think that an NPE from an item that can corrupt and rewrite the entire vault should be something that you should consider fixing.

**Comment by drtshock** [comment]
No since it is placing an invalid item in the vault. It's important that the error is there.

**Comment by Azfaloth** [comment]
i agree with the necessity of the error. Though I personally would have felt better if it caught the exception gracefully and printed an error to console and didnt save that particular item. Rather than stacktrace plus wiping the vault in question. But alright, I will try to get the plugin developer to fix it. He seems clueless though. In any case, thank you for your time.
