### ISSUE TITLE
Permissions Are Messing Up!

### ISSUE THREAD

**Issue by Stevie123454321** [drtshock/PlayerVaults#130]
So, I have recently installed this plugin to my server, i must say, i love it. But for some reason even though im not giving the group the permission to open with the command /pv 1, they are still able to do so, here are the permission i have given them (for PV)
playervaults.signs.use
playervaults.amount.6

and when I put it in like this

playervaults.signs.use:true
playervaults.amount.6:true
playervauts.commands.use:false

It will not let them open a sign or use the command.

So the node for commands isnt even there, and I looked in config, and there isnt anything about it, please help?
-Stevie

**Comment by kashike** [comment]
Please [open a new issue](https://github.com/drtshock/PlayerVaults/issues/new) if this is still an issue.
