### ISSUE TITLE
Shift Clicking banned items into Player Vaults

### ISSUE THREAD

**Issue by Nickshelton80** [drtshock/PlayerVaults#131]
So it seems that if you shift click a banned item into your vault, it bypasses the banned item list. It won't let you take them out though, So I'm assuming the plugin only listens for a drag and drop event or something.

It's not a huge deal but I figured I would report this :)

**Comment by magemaniac33** [comment]
I'm having the same issue however mine is the opposite.
Players cannot shift click items as it's blocked...
If they click and drag it works fine, but when players try to get the items out it doesn't work.


Using version: PlayerVaults v3.5.7-b187
