### ISSUE TITLE
ERROR Could not pass event InventoryClickEvent to PlayerVaults v3.5.7-b${BUILD_NUMBER}

### ISSUE THREAD

**Issue by Castro0996** [drtshock/PlayerVaults#135]
17.01 14:22:41 [Server] INFO ... 15 more
17.01 14:22:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
17.01 14:22:41 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
17.01 14:22:41 [Server] INFO at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source) ~[?:?]
17.01 14:22:41 [Server] INFO at com.drtshock.playervaults.listeners.Listeners.onClick(Listeners.java:121) ~[?:?]
17.01 14:22:41 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()Lorg/bukkit/inventory/Inventory;
17.01 14:22:41 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_80]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_80]
17.01 14:22:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_80]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1564) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[CraftBukkit188.jar:git-Bukkit-18fbb24]
17.01 14:22:41 [Server] INFO org.bukkit.event.EventException
17.01 14:22:41 [Server] ERROR Could not pass event InventoryClickEvent to PlayerVaults v3.5.7-b${BUILD_NUMBER}

**Comment by Castro0996** [comment]
Server: CraftBukkit 1.8.8

**Comment by kashike** [comment]
If this is still an issue with the most recent version, please open a new issue.
