### ISSUE TITLE
Wrong Vault Size On First Join

### ISSUE THREAD

**Issue by WFloydBoy** [drtshock/PlayerVaults#136]
Been receiving reports from players who have joined for the first time having 6 rows in the vault (wrong size) and after re-logging having 1 row (correct size).

PlayerVault's Version: https://gyazo.com/741a5edbc4d37bcb0f90057bc7b5a0b5 "PlayerVaults v3.5.7-b${BUILD_NUMBER}"
Server Version: 1.8.8 PaperSpigot

**Comment by kashike** [comment]
If this is still an issue with the most recent version, please open a new issue.
