### ISSUE TITLE
/pvsign returns no messages, does not appear to function

### ISSUE THREAD

**Issue by hagfelsh** [drtshock/PlayerVaults#137]
Hello!  I read through all the rest of the sign issues in the issue tracker, but they all appear to have resulted in code fixes.  I can't tell if I'm running the latest release... haven't figured out where the version is listed here!

On boot, these are the versions of CraftBukkit & PV that are reported:
minecraft server version 1.8.3
v3.5.7-b${BUILD_NUMBER}

I can't actually tell what version of CraftBukkit I'm running, but the filename is craftbukkit-1.8.3-R0.1-SNAPSHOT-latest.jar, so that's probably a decent hint.

Am I operating on in compatible versions?  /pv # and /pv <player> # both work perfectly.  Only the signs function seems to simply not be acknowledged.   It's in the commands list (tab complete works) but no message appears one way or another.  I even enabled debug true in the conf file but that made no change.

Any insight would be very appreciated :)

h

**Comment by drtshock** [comment]
https://ci.drtshock.net/job/PlayerVaults/ run the top version there.

**Comment by hagfelsh** [comment]
That did it!  Great!  

This is a lovely plugin, thank you for going to the effort of writing and documenting it so well :)

**Comment by drtshock** [comment]
thanks :)
