### ISSUE TITLE
Playervaults empty with 0k files

### ISSUE THREAD

**Issue by FatherWh0** [drtshock/PlayerVaults#139]
I've just added playervaults to a new server. Several players have reported their pv has come up empty. These players were using pv without issue then, the next morning, their pv  are empty of all contents.. Each time they open /pv 1 it charges them for a new vault. I've found for each of them there is a 0k file in the uuidvaults directory Currently there are 7 files. Five are 0k. One is 11k with only the entry "vault1: {}" in it. One file has the player's contents.

Using version 3.5.7

Here is a copy of my config: http://pastebin.com/rjUC6fkA

Your help would be greatly appreciated and thank you for an awesome plugin.

**Comment by drtshock** [comment]
Are there any errors in the server log?

**Comment by FatherWh0** [comment]
There are no errors. I did see several entries in startup showing playervaults being cleaned up despite the setting for 183 days. However the 0k vaults are still present.

If this info helps, pv is indicating the players with 0k files do not have playervaults. Those players are charged if they open /pv 1 and if I attempt to open their vault it reports the vault does not exist.

**Comment by FatherWh0** [comment]
I added Playervaults back on my server for testing. I wiped all files clean and am using the same config except I changed costs to 0 and lastedit to 183.

Each time I restart there are cleanup entries. On the last restart two vaults were cleaned up that had contents resulting in empty vaults.

I have disabled cleanup and will let you know if that remedies the issue.

**Comment by drtshock** [comment]
thanks for the update

**Comment by FatherWh0** [comment]
with cleanup disabled there haven't been any pv coming up empty. It does look like the cleanup function was at fault. Sry I didn't realize this sooner. One of my testers gave me bad intell that misled my investigation into the issue. I can say for certain now that every pv that came up empty had an cleannup entry on startup.
Thank you for your help and for an awesome plugin.

**Comment by drtshock** [comment]
It would log that it's deleting in the cleanup so perhaps that was the issue? Or I think it was that we had a bug that the cleanup was set to run sooner than expected.
