### ISSUE TITLE
Language file can't be edited.

### ISSUE THREAD

**Issue by AdxmMC** [drtshock/PlayerVaults#143]
I was trying to customize the language file, after Im done it gives me a message "the config was reloaded by another program" this only applies to PlayerVaults, no other plugins.

**Comment by kashike** [comment]
Are you reloading your server? How are you trying to load the new translations?

**Comment by AdxmMC** [comment]
Yes I'm reloading my server...
I used notepad++ to edit it.

**Comment by kashike** [comment]
Don't reload. Stop and start again.

**Comment by AdxmMC** [comment]
Already tried...
So i stopped the server and i edited the config, then i started it again and this message pops and it doesnt config.
http://prntscr.com/a7ddfi

**Comment by drtshock** [comment]
Don't edit while the server is on. You need to edit and SAVE while the server is off.

**Comment by AdxmMC** [comment]
You can't read? I said that I edited it while it's stopped and once I start it, it doesn't change.

**Comment by drtshock** [comment]
Then you're doing something wrong :)
