### ISSUE TITLE
/pv 1 dublicate and take double the money

### ISSUE THREAD

**Issue by Maxswe99** [drtshock/PlayerVaults#145]
when you do /pv 1 it says it cost the amount i put in, but it charge it again like 2 times every time when you do /pv 1. ex. if i do /pv 1 it cost 30k$ then it charge again so it cost 60k$

![screenshot_2](https://cloud.githubusercontent.com/assets/17504633/13366531/28b140fe-dcdc-11e5-8f48-a21ef962d2f6.png)

code: http://pastebin.com/mA0eU4H5

**Comment by drtshock** [comment]
Which version of playervaults?

**Comment by Maxswe99** [comment]
newest one

**Comment by drtshock** [comment]
which version?

**Comment by Maxswe99** [comment]
still newest version

**Comment by drtshock** [comment]
which version number?

**Comment by Maxswe99** [comment]
3.5.7
Den 29 feb 2016 00:39 skrev "Trent Hensler" <notifications@github.com>:

**Comment by drtshock** [comment]
Can you paste the server log when this happens?
