### ISSUE TITLE
Can't access player vaults while they are offline

### ISSUE THREAD

**Issue by juust1n** [drtshock/PlayerVaults#146]
I can't seem to access a players vault while they are offline, this is pretty important to me because I run a PvP server and need to make sure people aren't cheating. I use player vaults 1.7.10 and whenever I type /pv name 3 while the player is offline, it just says "Cannot find player name"

**Comment by drtshock** [comment]
Increase your usercache.

**Comment by juust1n** [comment]
sorry to bother you again, but if you help me out with details ill donate to your plugin. If I increase the user cache, that'll let me players bring over items to a brand new server in their /pv 3 and check offline vaults when I transfer the plugin? its going from a 1.7.10 server over to a 1.8.8 too, so I'll have to switch the .jars over. Is the usercache a setting in the player vaults plugin itself? it sounds like it would be some setting that chooses the number of user files that stay cached after they log out. I did find a file in the main directory called usercache.json, along with an option to increase the user-cache-size in spigot.yml also found in the main directory. I appreciate you getting back to me so soon.Date: Tue, 1 Mar 2016 12:44:09 -0800

**Comment by drtshock** [comment]
Telling me that you'll donate if I help fix your arbitrary issue makes me want to completely ignore you. I'm not a slave to your $5 or w/e it would be.

The usercache setting is in spigot.yml. It is what matches uuids to names for players that have played before but aren't currently online. You cannot open a vault of a player that hasn't logged in even if they have vault files from earlier.

**Comment by juust1n** [comment]
Alright, I've had to deal with a few other coders who wouldn't even speak to me unless they were getting some sort of money, and I guess you obviously aren't like that which I respect. This is my first time messing with the server so I want to make sure its right and I don't screw anything up for players. I simply change the user-cache-size to a bigger number for ex 2000 and I'll be able to access a players vault who's joined the server before and has items in their vault, even if they are offline, right?
This is how its supposed to work: - player joins server in 1.7.10, puts items in /pv 3- I change the host, update to 1.8.8, new spawn, everything, drag over the entire player vaults folder, and update the jar to 1.8.8.- turn on whitelist- I check each vault (about 80) to make sure no one has duped items- player joins the new server on 1.8.8- opens /pv 3 and all their items are insideso changing the user cache to a higher number would do this? ^
current stats in spigot.yml:  save-user-cache-on-stop-only: false  user-cache-size: 1000  int-cache-limit: 1024
Appreciate you getting back to me.
Date: Tue, 1 Mar 2016 16:58:45 -0800

**Comment by drtshock** [comment]
It doesn't work retroactively. They still need to have logged in to the server at some point + be in your usercache.

**Comment by juust1n** [comment]
I do know that, but if they are logged in 20 minutes ago but are now offline, will changing the usercache to a higher number allow me to look in their chest while they are offline? Also by changing the usercache, will that allow me to transfer items across servers if I just drag in the folder?

Date: Tue, 1 Mar 2016 17:30:29 -0800

**Comment by juust1n** [comment]
Found a solution to transferring items over, going to do it with a different plugin. I still do need to know how to access player vaults while they are offline, you said to update my usercache but its already at 1000, so it sounds like you think I don't have enough room? If you could give me just a little more detail I'll stop bothering you completely.

From: robertwalls117@hotmail.com
To: reply@reply.github.com
Subject: RE: [PlayerVaults] Can't access player vaults while they are offline (#146)
Date: Wed, 2 Mar 2016 01:28:20 +0000




Alright, I've had to deal with a few other coders who wouldn't even speak to me unless they were getting some sort of money, and I guess you obviously aren't like that which I respect. This is my first time messing with the server so I want to make sure its right and I don't screw anything up for players. I simply change the user-cache-size to a bigger number for ex 2000 and I'll be able to access a players vault who's joined the server before and has items in their vault, even if they are offline, right?
This is how its supposed to work: - player joins server in 1.7.10, puts items in /pv 3- I change the host, update to 1.8.8, new spawn, everything, drag over the entire player vaults folder, and update the jar to 1.8.8.- turn on whitelist- I check each vault (about 80) to make sure no one has duped items- player joins the new server on 1.8.8- opens /pv 3 and all their items are insideso changing the user cache to a higher number would do this? ^
current stats in spigot.yml:  save-user-cache-on-stop-only: false  user-cache-size: 1000  int-cache-limit: 1024
Appreciate you getting back to me.
Date: Tue, 1 Mar 2016 16:58:45 -0800
