### ISSUE TITLE
Duplication Glitch, 1.8. 

### ISSUE THREAD

**Issue by jwtuan** [drtshock/PlayerVaults#155]
My english very bad, i try to explain.
1. Player stan on wool carpet, wool carpet on water.
2. Player go away ( like spawn..)
3. Player use /back to back to wool carpet, now they have glitch
4. player open vault /pv 1 and take item (items they want to duplicate) from vault to inventory (still stand on wool carpet)
5. player logout
6. player login, items on inventory and  /pv 1 

I use:
- PaperSpigot 1.8.8
- EssentialsX build 268
- PlayerVault  3.5.6

**Comment by drtshock** [comment]
You're more than 2 versions behind. Please update.
