### ISSUE TITLE
Can still place emeralds in pv even when its blocked in config.

### ISSUE THREAD

**Issue by Duqino** [drtshock/PlayerVaults#158]
Hello,

I got a problem and i hope you can fix this ASAP. This will cause problems with my economy.

Should we even use this? If left to false, the list won't do anything.
blockitems: true

Only effective if the above option is true.
blocked-items:
- EMERALD_BLOCK
- EMERALD

Pls fix this!

Thanks!

Duqino / Dutchy.

**Comment by Duqino** [comment]
Any idea when this can be fixed?

King regards,

Duqino.

**Comment by drtshock** [comment]
Which version of playervaults and spigot were you on?

**Comment by Duqino** [comment]
Spigot -> https://gyazo.com/d922ff6f842c0c88e44f07c02a271f4a

pv -> R: v3.5.7 for 1.8.1 Sep 17, 2015

Not sure were i can see that in-game. Or in the config.

**Comment by drtshock** [comment]
Does this work on the latest dev build?

**Comment by Duqino** [comment]
Dev build of playervaults?

**Comment by drtshock** [comment]
Yeah https://ci.drtshock.net/job/PlayerVaults/

**Comment by Duqino** [comment]
Just tried with the latest dev build and having the same problem.

Can place emeralds in the pv. But cant take it out. It just placing it back and telling me it blocked from vault.

**Comment by Duqino** [comment]
My players are complaining that the /workbench command isnt working any more. 

Im using the on from playervaults. Looks like its broken in de dev build.

**Comment by drtshock** [comment]
Yeah I removed the workbench command because essentials has it and it's pretty silly to include it in here I think.

**Comment by Duqino** [comment]
Any idea when the problem will be fixed?

**Comment by Duqino** [comment]
Any idea?

**Comment by Duqino** [comment]
Joehoe?
