### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by Curtis3321** [drtshock/PlayerVaults#159]
Hey, there is a dupe with this plugin.

If you use a certain paid hacked client you can bind it to run commands & timers.

If you set a bind to run /pv 1 and then run pv 1 3 seconds later you can duplicate the items.

https://gyazo.com/3d5ecf964f0db6cbd6554f3a9edcbd8f

**Comment by drtshock** [comment]
Can you reproduce this and tell me which version you are on + which spigot version are you on

**Comment by Curtis3321** [comment]
I am personally unable to reproduce simply because the client is a private payed client. 

PV version is v3.5.2 and 1.7 Spigot

**Comment by drtshock** [comment]
You're well behind. Update to the latest version of playervaults. 

Your description just doesn't make sense. Typing pv 3 seconds apart doesn't make sense to be able to dupe.
