### ISSUE TITLE
HideFlags for custom give items. Wipes the item stats. 1.9.2 (Paper) Spigot

### ISSUE THREAD

**Issue by Coldene** [drtshock/PlayerVaults#161]
Hi, thanks for reading this.
Great job fixing the skulls skins serialisation thing 
in that last update. Yay.

I see this issue may already have been reported recently but not specifically?

I use last dev version of PlayerVaults
Mod - Paper Spigot 1.9.2 build 616
PV Seems to work perfectly in 1.9+ except the below thingy.
I have a really mad server with heavy modification.
Plugins can have a hard time with the customisations.
Yours has performed admirably even with the below only exception.
I really do...truly know.. how mad translating 1.8 to 1.9 is. Well done, you.

## Any items with **HideFlags** are reverting to plain items.
Put one in /pv 1 close and open again. Any items you 
put in with HideFlags will wipe to plain items.
HideFlags is fairly common trick with custom items
and may be replicating this bug on several 1.9+ servers?
If item is to be unbreakable but not show "Unbreakable" .. hideflags.
Want a custom /give color faction shield without half mile of tooltip color tags? .. hideflags :8ball:  /win

http://minecraft.gamepedia.com/Tutorials/Command_NBT_tags
HideFlags is marked as a 1.8 thing but still works fine in 1.9
I tried all the different settings for each HideFlag. All cause the bug.

Example.
`give %a 442 1 {HideFlags:32,display:{Name:"§6♦§e§lPyrite Tower Shield§r§6♦",Lore:["§7Deflect III","§7Bash III","§0|","§cThis pyrite shield","§cbelongs to %a","§0|","§6This shield costs nothing.","§6If you lose it you can get","§6another by doing /c PVKShield","§0|","§630 Min Cooldown"]},ench:[{id:7,lvl:1},{id:70,lvl:5},{id:34,lvl:5}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:2,Operation:0,UUIDLeast:952764,UUIDMost:466709,Slot:"offhand"},{AttributeName:"generic.armor",Name:"generic.armor",Amount:4,Operation:0,UUIDLeast:140189,UUIDMost:880080,Slot:"offhand"},{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Amount:4,Operation:0,UUIDLeast:12199,UUIDMost:40790,Slot:"offhand"}],BlockEntityTag:{Base:0,Patterns:[{Pattern:gra,Color:11},{Pattern:gru,Color:1},{Pattern:flo,Color:14},{Pattern:bt,Color:14},{Pattern:tt,Color:14},{Pattern:sku,Color:11},{Pattern:bts,Color:11},{Pattern:tts,Color:11}]}}`

Error log in console.

`03.04 20:20:04 [Server] ERROR Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta for deserialization 03.04 20:20:04 [Server] INFO java.lang.IllegalArgumentException: ItemFlags([HIDE_PLACED_ON, HIDE_ENCHANTS, HIDE_UNBREAKABLE, HIDE_POTION_EFFECTS, HIDE_ATTRIBUTES, HIDE_DESTROYS]) is not a valid interface java.util.Set 03.04 20:20:04 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.getObject(CraftMetaItem.java:192) ~[patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:499) ~[patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at sun.reflect.GeneratedConstructorAccessor174.newInstance(Unknown Source) ~[?:?] 03.04 20:20:04 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_77] 03.04 20:20:04 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_77] 03.04 20:20:04 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem$SerializableMeta.deserialize(CraftMetaItem.java:157) ~[patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source) ~[?:?] 03.04 20:20:04 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77] 03.04 20:20:04 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77] 03.04 20:20:04 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:77) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:117) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:195) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:152) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:145) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:94) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:164) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:100) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:130) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:155) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) [PlayerVaults.jar:?] 03.04 20:20:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1381) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77] 03.04 20:20:04 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:810) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:720) [patched_1.9.2.jar:git-Paper-616] 03.04 20:20:04 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:619) [patched_1.9.2.jar:git-Paper-616]`

**Comment by cyberpwnn** [comment]
This is an issue on 1.8.8 also

**Comment by drtshock** [comment]
Should be fixed now.
