### ISSUE TITLE
When opening PV it activated luckyscratchpro and hands out free stuff hehe

### ISSUE THREAD

**Issue by larrycatania** [drtshock/PlayerVaults#164]
hi not sure what happening... this randomly starts happening to a player.... some people already have a PV and it happens... Genome a player never had a PV and created 1 for the first time and got this... just starts happening to peeps randomly have not been able to track down why:
http://pastebin.com/QF8fn550

**Comment by drtshock** [comment]
I believe your stack trace is unrelated but what does the title mean?

**Comment by larrycatania** [comment]
On Tue, April 12, 2016 12:11 pm, Trent Hensler wrote:
> I believe your stack trace is unrelated but what does the title mean?
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/drtshock/PlayerVaults/issues/164#issuecomment-209011489

Hi , It only happened when I opened /pv which then caused that to
fire...is it a luckycratchpro issue then?

Sincerely,

Larry

**Comment by larrycatania** [comment]
Posted also to dev NacOJerk since his stuff is involved, maybe its itemmaker
