### ISSUE TITLE
Blocked Items fails on click and drag

### ISSUE THREAD

**Issue by EthanRPro** [drtshock/PlayerVaults#166]
Currently I have SkULL_ITEM blocked for player vaults.

originally it functioned as intended, shifting clicking, clicking and dragging both denied. My problem was solved. Now with no errors I can find and just a reload clicking and dragging in is no longer denied EXCEPT for when trying to remove an item from a vault.

Shift clicking is still blocked in when both trying to add and remove from vaults

**Comment by drtshock** [comment]
So it used to work but doesn't now? Can you tell me which version of playervaults / spigot that it broke on?
