### ISSUE TITLE
Dupe Bug please fix asap

### ISSUE THREAD

**Issue by BlueDemonic** [drtshock/PlayerVaults#169]
Hey, there is a dupe with this plugin.

If you use a certain paid hacked client you can bind it to run commands & timers.

If you set a bind to run /pv 1 and then run pv 1 3 seconds later you can duplicate the items.

PV version is v3.5.6 and 1.8 paperSpigot
http://prntscr.com/b41wk6

**Comment by drtshock** [comment]
Update

**Comment by BlueDemonic** [comment]
i have the lasted update what one do i download
