### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by BlueDemonic** [drtshock/PlayerVaults#170]
Hey, there is a dupe with this plugin.

If you set a home on a lillypad then move away then put something in your pv then go back to your home and run /pv 1 and then take the item out and close the pv it will be in your inv and still in the pv = you can duplicate the items. please fix this asap
and one more dupe 
My english very bad, i try to explain.
1. Player stan on wool carpet, wool carpet on water.
2. Player go away ( like spawn..)
3. Player use /back to back to wool carpet, now they have glitch
4. player open vault /pv 1 and take item (items they want to duplicate) from vault to inventory (still stand on wool carpet)
5. player logout
6. player login, items on inventory and /pv 1

I use:

PaperSpigot 1.8.8
1.8.8 PaperSpigot
http://prntscr.com/b6226i
http://prntscr.com/b637lx

**Comment by drtshock** [comment]
update
