### ISSUE TITLE
playervaults duplication

### ISSUE THREAD

**Issue by Disorbs** [drtshock/PlayerVaults#171]
so I heard about this after I found out a member had dozens of keys and diamond blocks and he
told be how to do it and I tried it and it worked

saw another user post this and its exactly what he said
(If you set a bind to run /pv 1 and then run pv 1 3 seconds later you can duplicate the items.)

and yes its a solid block/key i can use and place it down

currently making a video

https://www.youtube.com/watch?v=mtxjQj7ZZ1M

currently 1 version behind so i hope this was the issue but idk

**Comment by drtshock** [comment]
update
