### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by ItsMonkeyyy** [drtshock/PlayerVaults#173]
1. Throw an enderpearl pretty far
2. While the enderpearl is in the air, open up your vault
3. Keep the vualt open until the pearl lands
4. Once the pearl lands and you teleport, take away items you want to dupe from the vault
5. Close inventory
6. Open inventory and all the items you had previously taken out (which are still in your inventory) are now back in the vault

**Comment by drtshock** [comment]
On which version of spigot and playervaults?

**Comment by kashike** [comment]
@drtshock https://github.com/drtshock/PlayerVaults/commit/1421c2bf158b4640ae12eb2cc049ef5639553f56 :)

**Comment by kashike** [comment]
https://github.com/drtshock/PlayerVaults/commit/63ef227a7d23daa31f450a50a775b8acdb0e3ed0
