### ISSUE TITLE
Permissions Not Working

### ISSUE THREAD

**Issue by DonovanD07** [drtshock/PlayerVaults#177]
Im Running A 1.9 CraftBukkit Server 

_192.99.38.48:25632_

the permissions

**playervaults.ammount** _and_
**plyervaults.size** _and_
**playervaults.command.use** _and_
**all other permissions**

the only one that works is
**playervaults.workbench**

**PLEASE** i need to open my server soon... and i cant with this bug...

**Comment by drtshock** [comment]
amount *

**Comment by DonovanD07** [comment]
Thank you

**Comment by NurseJosh** [comment]
Perms are working fine on my server. It's probably on your end.
