### ISSUE TITLE
PlayerInteract error

### ISSUE THREAD

**Issue by TheIronMinerLv** [drtshock/PlayerVaults#178]
Hello!

I tried many versions of PlayerVaults, all have this problem - when I click on sign/open player vault with sign, it spams this error in console:

`31.05 14:07:39 [Multicraft] Skipped 28 lines due to rate limit (30/s)
31.05 14:07:29 [Server] ERROR Could not pass event PlayerInteractEvent to PlayerVaults v3.5.7-b${BUILD_NUMBER}
31.05 14:07:28 [Server] INFO ... 17 more
31.05 14:07:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
31.05 14:07:28 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
31.05 14:07:28 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
31.05 14:07:28 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
31.05 14:07:28 [Server] INFO at com.drtshock.playervaults.listeners.SignListener.onInteract(SignListener.java:97) ~[?:?]
31.05 14:07:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:176) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO Caused by: java.lang.NullPointerException
31.05 14:07:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
31.05 14:07:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
31.05 14:07:28 [Server] INFO org.bukkit.event.EventException`

Btw I'm using 1.8.8 server, so please fix this!

**Comment by drtshock** [comment]
Update from the CI

**Comment by TheIronMinerLv** [comment]
What does that mean?

**Comment by drtshock** [comment]
update https://ci.drtshock.net/job/PlayerVaults/ :)
