### ISSUE TITLE
Signs not working

### ISSUE THREAD

**Issue by tylerthecreeper2** [drtshock/PlayerVaults#179]
I tried using /pvsign and nothing returns, I was looking at a sign and typed it how it says on the plugin page, "/pvsign #" so I tried /pvsign 1, tried clicking the sign, nothing happens.

I'm using build 201.

**Comment by drtshock** [comment]
Can you paste the server log when you're trying to do this? And did it work on previous versions?

**Comment by tylerthecreeper2** [comment]
All that console says is that I ran the command, there's no errors.

I'll have to downgrade real quick and see if it worked in a previous version.

**Comment by tylerthecreeper2** [comment]
It does work on previous versions.

**Comment by drtshock** [comment]
Which version did it break on?

**Comment by tylerthecreeper2** [comment]
Sorry, I got it to work. I deleted my player vaults folder and it now works.
