### ISSUE TITLE
Signs keep unbinding

### ISSUE THREAD

**Issue by NurseJosh** [drtshock/PlayerVaults#180]
If I place a sign or interact with a sign around a vault sign it unbinds the vault sign.

**Comment by TheIronMinerLv** [comment]
I have this issue too sometimes

**Comment by drtshock** [comment]
Can you paste server logs when this happens?

**Comment by NurseJosh** [comment]
I figured out my problem. It was my mods with block break perms in the region accidentally breaking the sign. When I changed the server to deny block breaking in my vault even if a regular user broke the sign and world guard protected it the sign stayed up so it's fixed now. Thanks!
