### ISSUE TITLE
Empty files?

### ISSUE THREAD

**Issue by L4BORG** [drtshock/PlayerVaults#181]
I'm just wondering why PlayerVaults plugin is generating empty files for every player that ever joined the server? (even if they don't have permissions to use PV) Why not only create files when there's something to store?

**Comment by kashike** [comment]
Are you using the latest version?

**Comment by L4BORG** [comment]
I was using PlayerVaults v3.5.8-SNAPSHOT-b195, just updated to latest version, my bad. Do I have to manually remove old files?

**Comment by kashike** [comment]
Yes.
