### ISSUE TITLE
Player Vaults Dupe Glitch

### ISSUE THREAD

**Issue by ItsDovah** [drtshock/PlayerVaults#184]
While a player is in an enemy claim (or somewhere they cannot build) they can get themselves stuck in a lilly pad and literally keep opening and closing the menu which keeps duplicated items. If you would like more information I could send a video or a more detail explanation on it but for right now I had to disable it from my server because it started ruining my economy and I also was using the latest version from spigot

**Comment by drtshock** [comment]
Update to https://ci.drtshock.net/job/PlayerVaults/
