### ISSUE TITLE
PlayerInteract error

### ISSUE THREAD

**Issue by TheIronMinerLv** [drtshock/PlayerVaults#185]
Every time someone opens vault, this error shows up in console
`07.06 14:01:30 [Server] INFO Caused by: java.lang.NullPointerException
07.06 14:01:30 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
07.06 14:01:30 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1411) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:852) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot18.jar:git-Spigot-e4d4710-e1ebe52]
07.06 14:01:30 [Server] INFO org.bukkit.event.EventException
07.06 14:01:30 [Server] ERROR Could not pass event InventoryCloseEvent to PlayerVaults v3.5.6-b181`

**Comment by drtshock** [comment]
Can you paste the entire exception in a pastebin?

Also, update to the latest dev build https://ci.drtshock.net/job/PlayerVaults/

**Comment by TheIronMinerLv** [comment]
Here you got pastebin http://pastebin.com/LG3zymqb

And when I updated, it showed similar error, and PlayeVaults cost didn't work (players was able to access vaults all vaults without purchasing them).

**Comment by TheIronMinerLv** [comment]
Ok, then now I'll give you "full" error (nothing more doesn't show up in console): http://pastebin.com/Pn2a2F7K

So I should update plugin or what?

**Comment by drtshock** [comment]
We need what's below the null pointer exception line. That's still not showing everything...
But yes, please update.
