### ISSUE TITLE
LilyPad Dupe Glitch still happens..

### ISSUE THREAD

**Issue by StillDupeGlitchLmao** [drtshock/PlayerVaults#186]
LilyPad Dupe Glitch still happens.. im using https://ci.drtshock.net/job/PlayerVaults/201/

**Comment by StillDupeGlitchLmao** [comment]
paperspigot 1.8.8 is my version

**Comment by drtshock** [comment]
Can you explain the glitch

**Comment by StillDupeGlitchLmao** [comment]
Well, you use a lilypad and glitch into it. Then you just do /pv 1

**Comment by drtshock** [comment]
How do you glitch into it?

**Comment by StillDupeGlitchLmao** [comment]
You do the lilypad, just like everyone else is telling you.. then you take what you want to dupe out of it. Then QUIT the server, and re join. then what ever you taken out is now in your inventory and in your pv once again

**Comment by HunterGPlays** [comment]
You can download a patch [here](https://terrocidepvp.net/files/PlayerVaultsDupePatch.jar). [Here](https://www.youtube.com/watch?v=wyASnKkWRiQ) is a video on how it happens.

**Comment by StillDupeGlitchLmao** [comment]
Thanks, but it also works with other things such as carpets. Also there is another method of this dupe where you log out

**Comment by HunterGPlays** [comment]
I think I may know the issue. It may be to do with the teleport listener ignoring cancelled events. I'll test this out on my own fork and PR it if that's the issue.
