### ISSUE TITLE
PlayerInteract...

### ISSUE THREAD

**Issue by TheIronMinerLv** [drtshock/PlayerVaults#187]
I'll be short - I'm using newest spigot 1.8.8 and newest PlayerVaults from dev (#201 currently). When I click on a sign, it shows this error in console (there is NOTHING more, idk how to get more info from that error): http://pastebin.com/5AdQYhk3

Please help!

**Comment by TheIronMinerLv** [comment]
bump?

**Comment by TheIronMinerLv** [comment]
Then please TELL ME HOW TO GET ALL ERROR FROM CONSOLE

**Comment by drtshock** [comment]
This one is the full error so thanks. But please chill, I'm on vacation visiting family for a few days.
