### ISSUE TITLE
PlayerVaults Error (/pv 1)

### ISSUE THREAD

**Issue by Disorbs** [drtshock/PlayerVaults#189]
So some players randomly couldn't use their pvs and i recently updated to the latest version
from Devs site now it works but they dont have the items anymore but the error still happens?

(/pv 1)
pastebin - http://pastebin.com/ZRdyWCjv

**Comment by drtshock** [comment]
Which version of spigot are you on? Can you paste the file of the players that are having issues?

**Comment by Disorbs** [comment]
Hello and it is the latest one (Build #202)

and here is the playervault of the person - http://pastebin.com/KNqzbRZf

**Comment by Disorbs** [comment]
hello anything?

**Comment by drtshock** [comment]
paste no longer available

**Comment by Disorbs** [comment]
oh sorry here you go - http://pastebin.com/FSAmrxJH

**Comment by kashike** [comment]
Please [open a new issue](https://github.com/drtshock/PlayerVaults/issues/new) if this is still an issue.
