### ISSUE TITLE
OP can't see items in vault of player

### ISSUE THREAD

**Issue by tuanjr** [drtshock/PlayerVaults#190]
just update to latest build 202 run in PaperSpigot 1.9.2, now OP can't see what items in vault of player, (still can open, but see nothing).

> in previous build, i'm op, and i can see item in vault of player with command: /pv player-name number

**Comment by drtshock** [comment]
Can you describe exactly the command you are executing, if the other player is currently in the vault or not, and then what you see and what you expect to see?

**Comment by tuanjr** [comment]
In previous version,  If player drtshock has pv 1, as OP i can run command: /pv drtshock 1 to see pv1 of drtshock. Now,  in lates version, drtshock has pv 1 with full items,  but when i run /pv drtshock 1, i see empty pv.

**Comment by drtshock** [comment]
Are you sure that the vault you are viewing has items in it? I can't reproduce this. It works fine..

**Comment by tuanjr** [comment]
I'm sure,  im login 2 acc to tested.  And,  one more things,  in previous version,  if player doesnt has pv,  example pv 3, so when i try to open their vault with command: /pv drtshock 3, i get message "player doesnt has this vault".  Now,  i can open pv 3 (empty),  dont get above message,  but pv is empty.
I run on paperspigot 1.9.2, is it cause?

**Comment by drtshock** [comment]
The second part is expected.

The first part works fine locally for me..

**Comment by tuanjr** [comment]
Sorry for my bad english, what is your meant?
btw, i just tested again, so issues not cause by PaperSpigot
it's issues of build 202, build 195 still work fine.
Can you see that: http://imgur.com/a/qtf8G

**Comment by drtshock** [comment]
Hm, I ran it on the latest dev build and having the same issue. Thanks for catching that. I'll look into it.

**Comment by drtshock** [comment]
Here ya go :)

**Comment by drtshock** [comment]
Grab it from https://ci.drtshock.net/job/PlayerVaults/

**Comment by tuanjr** [comment]
Still one more things, in build 195, if Player doesn't has PV then when OP try to open players' pv, it's show message like this:
![t](http://i.imgur.com/QEK673i.png)
but now, if player doesn't has PV, OP still can open player's PV (but pv is empty)

**Comment by drtshock** [comment]
That's currently a limitation of how I'm working with letting other plugins hook into playervaults. I'm aware of this and will come up with something. You can still do `/pv name` to get a list of their vaults.
