### ISSUE TITLE
Players' vaults sometimes clear between viewing ShopGUI+ and Tinkerer&Enchanter!

### ISSUE THREAD

**Issue by Chapperszz123** [drtshock/PlayerVaults#192]
Players' vaults are getting replaced by the items in the ShopGUI+ plugin and the TinkererandEnchanter plugin.... Players on my server have lost a lot of items and it is getting very stressful!

**Comment by drtshock** [comment]
can you please elaborate, provide logs, versions, links to the actual projects, etc.

Give exact steps to reproduce and also what is the expected behavior.

**Comment by Chapperszz123** [comment]
Well, I haven't experienced this myself, But my players have. I'm not sure where to find the logs and if it would show on the logs, The Version is the newest (I don't know where to find what version it is). The glitch happens by someone doing, for example, /shop, the GUI for the shop comes up, They leave the shop and go into their Pv, and it copies the GUI into their vault. This aswell happens with the TinkererAndEnchanter plugin, where the /enchanter GUI is copied into their vault. Sorry for not adding logs etc, but I'm not really sure were to find them, the plugin is a bit idk? Muddled?

**Comment by drtshock** [comment]
Please report it when you can see the issue yourself and paste logs. It just goes in the same server log as everything else.
