### ISSUE TITLE
Player Vaults Dupe Glitch Cont.

### ISSUE THREAD

**Issue by ItsDovah** [drtshock/PlayerVaults#193]
Here is a video of the dupe glitch still being able to be done. I am updated to the latest version and everything. https://www.youtube.com/watch?v=JrrcFfHiI2I&feature=youtu.be

**Comment by drtshock** [comment]
Can you please describe it?

**Comment by ItsDovah** [comment]
Will everything is in that video, they glitch theirselves into a lilly pad ( in someone elses claim) and then they open their vault and the items dupe

**Comment by drtshock** [comment]
Update to the latest build from ci.drtshock.net
