### ISSUE TITLE
Duplication glitch help!

### ISSUE THREAD

**Issue by U2EZKid** [drtshock/PlayerVaults#194]
Hello,

I am currently using PlayerVaults and people can duplicate items that are in they PV! They do this by enderperaling into the sky before its landed toing /pv 1 and when it has landed they throw the item out of they pv and then close they pv and open it again and even though the item has been thrown out its thrown out and its still in the pv!

Many Thanks
play.rougefactions.com

**Comment by drtshock** [comment]
update to the latest version on ci.drsthock.net

**Comment by U2EZKid** [comment]
Nope dosent fix it

**Comment by U2EZKid** [comment]
https://youtu.be/DGjWN_iYcNc

**Comment by drtshock** [comment]
That happens on https://ci.drtshock.net/job/PlayerVaults/203/ ?

**Comment by U2EZKid** [comment]
Yes it also happens on the link you sent me the newest one
