### ISSUE TITLE
Duplication Glitch (AGAIN) - With Enderpearls

### ISSUE THREAD

**Issue by StillDupeGlitchLmao** [drtshock/PlayerVaults#195]
Yeah.. again dude.

This is really getting out of hand.

Ok, so get enderpearls. Put something in a vault, example: /pv 1
Throw a enderpearl, before landing do /pv 1 - take the item out after landing and then close the vault. Then do /pv 1 again and you now have a duplicated item. This is working on the **LATEST BUILD**.

So don't say to update dude, stop being lazy and work on it. You only work on your paid plugins. Please care for the other great ideas too, why not make playervaults a paid plugin?

Works on Build 201, 202 and 203 (This is after the patch for the lily-pad glitch).

**Comment by StillDupeGlitchLmao** [comment]
@vemacs Do you know how to solve this? @drtshock doesn't seem to know how to fix duplications lol

**Comment by vemacs** [comment]
OK, you can have a refund.

**Comment by StillDupeGlitchLmao** [comment]
lool @vemacs thanks man i'll test these changes now.

**Comment by StillDupeGlitchLmao** [comment]
Confirmed this fixed it.. I hope there isn't another stupid dupe glitch. It's causing me to make so many back ups each hour xD Because it's factions.

**Comment by vemacs** [comment]
Close the issue then....?
