### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by KraytonMC** [drtshock/PlayerVaults#198]
Is there a way to fix this dupe glitch?
Version: Latest
Dupe Evidence:
https://www.youtube.com/watch?v=tBqwsMmyoNM&feature=youtu.be

**Comment by drtshock** [comment]
Which version is latest? https://ci.drtshock.net grab 205 from there.

**Comment by kashike** [comment]
Please [open a new issue](https://github.com/drtshock/PlayerVaults/issues/new) if this is still an issue.
