### ISSUE TITLE
Special items data is wiped when items are placed into /pv

### ISSUE THREAD

**Issue by Deiscorides** [drtshock/PlayerVaults#200]
Items from this plugin are being turned into standard water bottles when placed into /pv

http://dev.bukkit.org/bukkit-plugins/brewery/

**Comment by Deiscorides** [comment]
I filed a ticket with them as well:

https://github.com/DieReicheErethons/Brewery/issues/135

**Comment by applessmillion** [comment]
Happens to me also, except with chests from the plugin CosmicChests
![yep](https://cloud.githubusercontent.com/assets/18158365/16539070/7d245cd4-4005-11e6-93fd-cf55cd96efa1.gif)

**Comment by applessmillion** [comment]
I've found any item with anything for hiding flags (hiding enchantments & modifiers) will get completely wiped. I gave myself a few banners through commands (With "HideFlags:44" at the end to hide all the lore) and they were reset to white banners when I closed and reopened the vault.

**Comment by drtshock** [comment]
Correct. It only serializes what Bukkit knows about.
