### ISSUE TITLE
Vaults deleting themselfs

### ISSUE THREAD

**Issue by grandmen123** [drtshock/PlayerVaults#202]
We have an issue where player's vaults are being cleared and we have no idea why, there are also 0 errors in console

If you could give us a hand I would much appriciate it

Regards,
                 Grandmen123
                 NemeGaming Management

**Comment by drtshock** [comment]
Are you sure you have file write permissions? I'm not sure what else could be causing it..

**Comment by grandmen123** [comment]
Yep I'm sure about that

**Comment by drtshock** [comment]
Are the files empty after a player closes their vault?

**Comment by grandmen123** [comment]
the uuid vaults storage?

**Comment by grandmen123** [comment]
Those are empty, althought backups arent

**Comment by Odie680** [comment]
Can confirm this happens, don't know why.

**Comment by drtshock** [comment]
file permission issues or something related.

**Comment by Odie680** [comment]
My friend, it's not that.
