### ISSUE TITLE
Can't fully edit other player's pvs as an admin

### ISSUE THREAD

**Issue by argentinaboy95** [drtshock/PlayerVaults#203]
I'll do my best to explain. To start off, it used to be that I couldn't open a player's vault if the player didn't have any items in it, it would always tell me it didn't exist. As of a few weeks ago I can open any numbered vault of a player, even if they don't have access that number pv or have anything in it. I've had this issue where I can /pv <name> and I can take stuff out of it or whatever, but the item stays in there for the player. Likewise when I try to (for example scam refund) an item and put it into his pv it never shows up for him but it is there for me(Before you say "oh maybe the player is lying to get free stuff" I've tested this and can provide a video if need be). This makes it impossible to remove unwanted items a player has in a pv, scammed items, etc. Is this a problem with my config or could it be the plugin itself?

**Comment by drtshock** [comment]
Can you paste server logs of this happening with playervaults in debug mode and then also your playervaults and spigot versions please (latest isn't a version, I need the actual version and build numbers).

**Comment by tuanjr** [comment]
i'm confirm this issues, in previous version, as OP, i can take items from Player Vault of Players, but now, with build 205, i can't take or give items to Player Vault (of players)
Please fix it.
