### ISSUE TITLE
[Suggestion] Remove the /vault alias

### ISSUE THREAD

**Issue by Tzzzt123** [drtshock/PlayerVaults#206]
Can you remove the /vault alias please? I need it for the plugin named Vault in my server!
Or how can I remove it?
Thanks

**Comment by ZombieHDGaming** [comment]
The plugin named Vault? You mean the "API (It's technically a vault.....bad pun. Milkbowl is responsible for that)"?

**Comment by m10653** [comment]
Depending how bad you need this changed, what you can do is open up the jar in winwar and edit the plugin.yml and remove the Alias, this only requires a text editor like notpad ++

**Comment by kashike** [comment]
As mentioned by @m10653, you can manually remove this alias from your JAR if you wish.
