### ISSUE TITLE
Vault Tiers

### ISSUE THREAD

**Issue by ZombieHDGaming** [drtshock/PlayerVaults#209]
Hi there,
this is just a suggestion for a feature, but what if you could make it so vaults could have tiers? Such as, starting with just a 9 slot vault, and slowly paying an upgrade fee that increases based on the next tier. So, just use like /pvupgrade (vault#), and you can confirm the upgrade or deny (Since people can't make up their minds).

And I know the first thing people would say is, "What about people who don't want tiers?!?! OMFG, wtf noob, go kys!", (btw, that is an exageration, but I feel like someone out there would say that) but let me stop you there. There can be a tier mode config option to enable or disable the upgrade feature. Essentially, an overkill boolean to say whether or not tiers are available on the server.

Anyways, I think this would be a cool feature, and I would love to see you implement this if you can :smiley: 

Cheers,
ZombieHDGaming

**Comment by drtshock** [comment]
You could do this with buying permissions :)
