### ISSUE TITLE
Feature Request: Support for StackableItems

### ISSUE THREAD

**Issue by FatherWh0** [drtshock/PlayerVaults#213]
In a world where apples fall off oak trees and we craft diamond we enjoy when things make sense. This includes the logic of being able to carry 64 one meter cubed stone blocks but only 16 snowballs and stew takes up a slot all to itself. Ok maybe we don't enjoy that logic so much. 

Superstacking is a thing. The plugin, StackableItems, https://dev.bukkit.org/bukkit-plugins/stackableitems/ is becoming a popular plugin for overcoming vanilla shortcomings. Unfortunately shift-clicking a superstacked item into an unsupported container causes a loss of items.  If PlayerVaults supported StackableItems' stacks this would be a great added feature. Alternatively, a configurable option to prevent shift-clicking into pv would allow admins of superstacking servers to prevent loss.

**Comment by drtshock** [comment]
So basically inventory sorting..

**Comment by FatherWh0** [comment]
If it recognized a superstack being shift-clicked into a pv and unstacked it that would be enough compatibility to prevent loss but not add any storage space. The issue is when a superstack is shift-clicked into a pv the pv takes the default amount and the rest is lost.  
Optionally, it would be support for stacking up to 127 of an item in each slot. Stackableitems stores it's config in plugins\StackableItems\Items.yml. Here's an example:
http://pastebin.com/HrHDiKpV
