### ISSUE TITLE
Items get disenchanted when put in pvs

### ISSUE THREAD

**Issue by VoxaDub** [drtshock/PlayerVaults#214]
http://hastebin.com/raw/epaqosawun
this error throws when people put enchanted items into their pvs
when they re-open them the items are disenchanted, pretty much resets the item.

**Comment by themanwithaplan2** [comment]
Yea this is a common problem reported by many people, the issue is that playervaults doesn't support the hide_flags attribute. The author has thus far neglected to fix this issue which is rather unfortunate.

**Comment by VoxaDub** [comment]
This is an ongoing problem and is fucking up my server, really need this fixed.

**Comment by themanwithaplan2** [comment]
Same

**Comment by VoxaDub** [comment]
http://hastebin.com/sumuyipegu.sm
still getting this problem on the latest build

**Comment by m10653** [comment]
This was patched. #220
