### ISSUE TITLE
Trying to get playervaults error free with 1.10.2 spigot.

### ISSUE THREAD

**Issue by 151baccardi** [drtshock/PlayerVaults#218]
You say : See Twitter. 

What is a twitter? Is there a link? Is there a solution? I don't know anyone named twitter.
I don't mean to be rude but nobody has ESP. We are not Psychic. Links work wonders and so do directions how to find answers. PlayerVaults is a wonderful plugin. What is wrong with minecraft that one can't just make a plugin that is good forever? We have plugins written for minecraft 0.0.1 ** that still work. It's frustrating to me because even though our server only has 744 plugins, updating them all would still be a pain even if it wasn't a mystery every time to find an update link. I am exaggerating of course. Anything over 100 plugins (like us) will cause a server owner like me to be a hopeless insomniac dreaming about meteor showers destroying our world. You're a cool DEV and make cool plugins. I hate seen broken things. I'm a fixomaniac. Sleepless and hopeless.

**Comment by drtshock** [comment]
That's why I write things to use the bukkit API so it only breaks if the API breaks. I don't hook into version specific code. You could go use the original version of playervaults and it'd still work just fine sans any issues I've fixed since.

You can download it on bukkitdev.
