### ISSUE TITLE
Incorrect number of slots.

### ISSUE THREAD

**Issue by dotapurex1** [drtshock/PlayerVaults#219]
Hello,

When a player first joins the server. They will have a full playervault, but in my permission system. I have it set so that they only get 1 row of slots. This doesn't take effect until either the server restarts or they relog. So, during this time that they have the full playervault, they will store their items in it and lose the remainder that isn't in the 9 slots due to this bug.

Thanks!

**Comment by mehboss** [comment]
I have this problem too, I am using permissions ex, glad I am not the only one! I hope they can find out the problem and fix it ASAP!

Spigot Version: 1.8.8

Pex Version: Latest dev build!

Errors:
N/A

**Comment by dotapurex1** [comment]
Hello,

The problem is not solved. We're not granting them 54 slots when they first join. Basically, if the player hasn't played before or if they are invalid, it's returning 54. What's the reason behind this check: player.hasPlayedBefore ?

**Comment by kashike** [comment]
https://github.com/drtshock/PlayerVaults/issues/221#issuecomment-241175799
