### ISSUE TITLE
Incorrect number of slots - Not fixed on ticket #219

### ISSUE THREAD

**Issue by dotapurex1** [drtshock/PlayerVaults#221]
Hello,

When a player first joins the server. They will have a full playervault, but in my permission system. I have it set so that they only get 1 row of slots. This doesn't take effect until either the server restarts or they relog. So, during this time that they have the full playervault, they will store their items in it and lose the remainder that isn't in the 9 slots due to this bug.

Reply to ticket: #219

The problem is not solved. We're not granting them 54 slots when they first join. Basically, if the player hasn't played before or if they are invalid, it's returning 54. What's the reason behind this check: player.hasPlayedBefore ?

Thanks!

**Comment by kashike** [comment]
The "has played before" check was removed in https://github.com/drtshock/PlayerVaults/commit/ee7d0439f5c26fb11ff26e8e6952ec3e744f77df, which is why #219 was resolved. Players which have not played before are no longer granted a max size of 54.
