### ISSUE TITLE
DUPLICATION GLITCH

### ISSUE THREAD

**Issue by mehboss** [drtshock/PlayerVaults#223]
There is currently a duplication glitch going around, I do not know any info on it but can you please add a delay option in the config so that when a player opens their playervault it takes 4 seconds of not moving sort of like ./spawn with essentials or something.

**Comment by drtshock** [comment]
which version of playervaults and which spigot version?

**Comment by mehboss** [comment]
I have the latest dev build and the latest spigot version so
Spigot: 1.8.7 I believe

**Comment by mehboss** [comment]
Will you be able to add a delay to it?

**Comment by drtshock** [comment]
what is the version number

**Comment by mehboss** [comment]
build #204

**Comment by mehboss** [comment]
????

**Comment by kashike** [comment]
Patience is a virtue.

**Comment by mehboss** [comment]
2 days later.

**Comment by mehboss** [comment]
:/ :-1:

**Comment by mehboss** [comment]
@drtshock hello?
