### ISSUE TITLE
playervaults permissions issue

### ISSUE THREAD

**Issue by VexMCServer** [drtshock/PlayerVaults#224]
in one of my donor groups I gave them these playervaults perms:
- playervaults.size.3
- playervaults.amount.1
- playervaults.commands.use
  but is still says that they don't have access to /pv 1?
  Am I doing something wrong?

**Comment by drtshock** [comment]
probably. can you paste your full permissions setup

**Comment by SebSailes** [comment]
Dear drtshock 

I am having the same problem with my server! I am using GroupManager and this is the command file for my VIP and DONOR rank:

Donor:
permissions:
    - -bukkit.command.kill
    - essentials.chat.color
    - essentials.chat.format
    - essentials.chat.magic
    - essentials.feed
    - essentials.fly
    - essentials.jump
    - essentials.nick.color
    - essentials.time.set
    - essentials.lightning
    - essentials.enderchest
    - essentials.workbench
    - playervaults.ammount.4
    - -playervaults.command.use
    - essentials.sethome.multiple.donator
    - pickupspawners.pickup 
    - pickupspawners.place
    - pickupspawners.allworlds

VIP:
permissions:
    - -bukkit.command.kill
    - essentials.nick
    - -playervaults.commands.use
    - playervaults.size.6
    - playervaults.ammount.2
    - essentials.sethome.multiple.vip
    - -playervaults.command.use

**Comment by AwwUwU** [comment]
yea how do i do my perms for my player vault?
