### ISSUE TITLE
Playervaults, small chance, big bug

### ISSUE THREAD

**Issue by OMGYES** [drtshock/PlayerVaults#225]
I was opening my pv, my friend logged in with the same account. I got kicked of course and it said "you logged in from another location", when I logged back in and opened one of my pv's, everything was gone.
I have 500 pv's and all 500 pv's are deleted with important stuff in it, I lost a special tool that costs 7.50 USD In real life because this :/

I think the chance is small that someone else is logging in when you are opening a pv but whenever it happens, everything is gone and that's what nobody wants

**Comment by drtshock** [comment]
Can you show the log files while this happens and also which version are you on?

**Comment by OMGYES** [comment]
No I can not and I think it's fixed. Hoi
