### ISSUE TITLE
Only 1 pv works.

### ISSUE THREAD

**Issue by SkilledPotato** [drtshock/PlayerVaults#229]
Hi there, I have 1 major problem with pv:

I have set it so donators have different amount of PV numbers and Members have none but for some reason every donator rank can only access /pv 1 and thank god the Member has no access to it.

In pex I put the perm under my Donator rank:

- playervaults.amount.1

and under my VIP perms I put:

- playervaults.amount.2

and each other donator rank 1 amount higher but for some reason each rank only has /pv 1.

Could this be due to 1 rank inherits the other? (In this case VIP inherits Donator perms).

If it would make life easier I can pastebin my pex config.

Carlos

**Comment by SkilledPotato** [comment]
fixed it myself due to your crappy supprt system. I put player.vaults instead of playervaults for whoever is wondering..

**Comment by drtshock** [comment]
my crappy support system led you to figure out that the ticket you posted had the correct permission node but your permission file didn't? nice
