### ISSUE TITLE
Playervaults Internal error Playervaults VER: version: 3.6.0-SNAPSHOT-b${BUILD_NUMBER}

### ISSUE THREAD

**Issue by dotapurex1** [drtshock/PlayerVaults#232]
Hello,

I've received a report from a player that they are getting an internal error when trying to open their vaults. I took a look at their vault and it shows this binary thing that seems out of place.

  '13': '{"==":"org.bukkit.inventory.ItemStack","type":"DIAMOND_CHESTPLATE","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":4,"DURABILITY":5},"display-name":"§8[§6§lBattleset§8]§b
    Chestplate"}}'
  '14': !!binary |-
    eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsImRhbWFnZSI6MiwidHlwZSI6IkRJQU1PTkRfQVhFIiwibWV0YSI6eyI9PSI6Ikl0ZW1NZXRhIiwibWV0YS10eXBlIjoiVU5TUEVDSUZJQyIsImVuY2hhbnRzIjp7IkZJUkVfQVNQRUNUIjoyLCJEVVJBQklMSVRZIjozLCJEQU1BR0VfQUxMIjozfSwibG9yZSI6WyLCpzdDdXJzZSBJIl0sImRpc3BsYXktbmFtZSI6IvCfkqlIeXBlckJvbGUiLCJyZXBhaXItY29zdCI6N319
  '15': '{"==":"org.bukkit.inventory.ItemStack","damage":17,"type":"DIAMOND_SWORD","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"FIRE_ASPECT":2,"DURABILITY":3,"DAMAGE_ALL":5},"lore":["§7Frozen
    I","§7§7Wither Aspect II","§7§7Poison II","§7§7Lifesteal I"],"display-name":"Hey!
    Sorry you can''t Pvp here!","repair-cost":7}}'
  '16': '{"==":"org.bukkit.inventory.ItemStack","damage":16482,"amount":30,"type":"POTION"}'

**Comment by dotapurex1** [comment]
- Seems like the issue still isn't solved from #207.  Will this be fixed anytime soon?

**Comment by Trickster489** [comment]
@dotapurex1 Not likely, author hasn't committed in 2 months, if you wouldn't mind sending me your server IP address I could connect and try to replicate the issue. If I successfully reproduce it, I can fork the project, commit the necessary fix, and build it for you.
