### ISSUE TITLE
/wb interferes with Essentials' /wb

### ISSUE THREAD

**Issue by GrizzsChannel** [drtshock/PlayerVaults#233]
Can you remove it in the next update?

**Comment by kashike** [comment]
This was removed a while ago (https://github.com/drtshock/PlayerVaults/commit/48206f552f6ec55a489ed6a00b71c25d7f67d5d8).

**Comment by GrizzsChannel** [comment]
When I download PlayerVaults, it still has /wb

**Comment by kashike** [comment]
You're downloading it from the wrong place, then. https://ci.drtshock.net/job/PlayerVaults/
