### ISSUE TITLE
Unlocking vaults

### ISSUE THREAD

**Issue by Aalscholver** [drtshock/PlayerVaults#234]
Best drtshock.

I want to use your player vaults plugin in my server, but I am encountering a problem that I cant seem to fix, I want people to be able to create a vault, but for a price. (5000$). So I set economy to true in the config. I made a sign thats lets you open a vault. So when someone clicks it it will take 5000$ of his account and create a vault for him.  But the problem is that when  someone doesn't put an item in it after he ''created'' it, the vault gets deleted. (Empty vaults get deleted). But it did cost him 5000$ to create it.
Is there a way I can let people unlock a vault for 5000$? Or let the vault don't delete himself when its empty.

Waiting on your awnser.

Best regards,
Lucas

**Comment by DataStoreRBLX** [comment]
Whilst I'm unsure on whether you can prevent the deletion, why not simply set the 'refund-on-delete' option to equate to the amount it cost to create the vault to begin with? So, set it to 5,000 - Then ,if the vault deletes, they get their money back. Just one way around the issue you're having.

**Comment by fordross** [comment]
Refunding the cost on deletion would solve that problem, but would completely defeat the economy integration altogether.  If I had sufficient funds, I could open 100 vaults ($500,000), and as long as i was able to clear them, my use for however long I had them would be refunded, wouldn't it?
