### ISSUE TITLE
Lily Pad / Carpet Dupe Glitch

### ISSUE THREAD

**Issue by PhantxmWolf** [drtshock/PlayerVaults#235]
There is a dupe glitch where if you set home on a carpet or lilypad WITH water underneath and then do /home [name] and get glitched into the lily pad / carpet. then you open your pv that you have the desired dupe item in. take it out and then close the pv. then re-open it and it's still there. Please help

Dupe video: https://youtu.be/n95hDvxwBaA

**Comment by drtshock** [comment]
Which version are you on? shouldn't be an issue with the latest on https://ci.drtshock.net/job/PlayerVaults/

**Comment by PhantxmWolf** [comment]
Oh its no big deal anymore i just used a patch off spigot and it fixed it.
