### ISSUE TITLE
Won't even load the jar.

### ISSUE THREAD

**Issue by JonoSando** [drtshock/PlayerVaults#237]
I've never had this issue before. A while ago the plugin was working fine but then it was producing a ton errors which I cannot recall. I removed the jar and replaced with the latest version. Now it won't even load! I have now tried every version but it still does not work. There are no errors in console when I attempt to load the plugin, very strange. I'm not that noob who doesn't know how to load a plugin either, so don't judge me on that. I firstly used /plugman load {name} but that didn't work. I then attempted to simply restart the server and still it does not load. Is there another plugin I need for this to work? It's not very clear. 

I would greatly appreciate any help!

**Comment by drtshock** [comment]
Try a new download and don't use plugman.
