### ISSUE TITLE
Duplicate glitch + video

### ISSUE THREAD

**Issue by voodootje0** [drtshock/PlayerVaults#238]
Dear the developers of PlayerVaults,

Could you fix this duplication glitch?
https://www.youtube.com/watch?v=KdMUimVXu0c&feature=youtu.be

Using playervaults build 207 and spigot 1.8.8

- voodootje0

@drtshock @kashike

**Comment by drtshock** [comment]
Can you reproduce this in online mode and show us the server logs please? It looks like your server isn't shutting down correctly as we force close and save vaults on shutdown as you can see here https://github.com/drtshock/PlayerVaults/blob/master/src/main/java/com/drtshock/playervaults/PlayerVaults.java#L127

**Comment by voodootje0** [comment]
The server was being rebooted by multicraft reboot task, like every other day.
