### ISSUE TITLE
Internal error when trying to access this pv - wont let anyone open it

### ISSUE THREAD

**Issue by VoxaDub** [drtshock/PlayerVaults#243]
For whatever reason I and anyone else is unable to open this players pv, idk whats in it or what would cause this.

http://hastebin.com/raw/yajoyilozu

**Comment by Faxed** [comment]
More than likely the same issue as seen in #277, which has been open since September-ish. 

One of the items in the player's vault likely has a 'HIDE-ATTRIBUTES' flag attached - The only way you'll be able to let them open that vault, for the moment, is by manually editing that out.
