### ISSUE TITLE
Playervaults blocked items feature

### ISSUE THREAD

**Issue by dotapurex1** [drtshock/PlayerVaults#244]
When this feature is enabled and you place an item in the playervault. The item gets placed in the vault but you cannot take it back out. 

Bug Replicate: Click drag and drop the blocked item in the playervault.

**Comment by OhNinjahs** [comment]
I'll replicate and fix this when I'm home.

**Comment by JohnCrafted** [comment]
It still exists.. I have tried to fix it my self but could not fix it.
