### ISSUE TITLE
PlayerVaults error when opening specific PV of a specific player

### ISSUE THREAD

**Issue by MinecraftAdmin** [drtshock/PlayerVaults#254]
Hello. PlayerVaults is throwing an internal error if I open a specific vault of a specific player. It is their Vault number 1 and here are the contents: http://pastebin.com/sSX5AJR5. I am using 3.6.0-B207
Oh and here is the console error that pops up when I try to open that vault: http://pastebin.com/xp46hA9t

**Comment by Mod-masta** [comment]
I have the exact same issues. It has only happened to 2 players.
