### ISSUE TITLE
Disable opening of vaults in specific worlds

### ISSUE THREAD

**Issue by Johandrex** [drtshock/PlayerVaults#256]
This isn't an issue, it's more of a suggestion.
It would be great if we had the possibility to disable vault opening in specific worlds.
I've seen a few other open tickets which suggests this feature, but since they haven't been touched in months I though that It'd be good to make a new ticket.

**Comment by Hwiggy** [comment]
Have you tried per-world permissions? I believe most popular permission plugins support it. That may be what you're looking for.
