### ISSUE TITLE
Player Vault Empty?

### ISSUE THREAD

**Issue by Cuinoh** [drtshock/PlayerVaults#257]
I've had 2 people complain now that their player vault has been cleared and that all their items are gone. When I tried doing /pv 1 {player name}, it states that "That vault does not exist!"

I'm running the newest version of player vaults and my server is spigot 1.8.8.

Please let me know if you need any other information.

**Comment by Hwiggy** [comment]
If the server is running offline mode for BungeeCord you may experience issues with PlayerVaults, as PlayerVaults use UUIDs for storing data, which may change on a per-login basis in offline mode. Make sure you have set bungeecord: true in your spigot.yml

If you are not using BungeeCord, I am unsure if there is a fix.
If your server is online mode, this may be a bug.
