### ISSUE TITLE
1.8.8 Confirmed Dupe 

### ISSUE THREAD

**Issue by Hwiggy** [drtshock/PlayerVaults#259]
Steps to replicate:
1. Put some nice items you want more of into a pv
2. Throw an enderpearl a bit far away (Far enough so you can type in the playervault command)
3. Open vault immediately after throwing enderpearl
4. On land, take the item out and close the vault
5. Re-open playervault

Spigot 1.8.8 PlayerVaults v3.5.6-b181

I am unsure if you're still supporting the 1.8 builds, but a fix would be greatly appreciated.
I assume this can be prevented by giving a warm-up on the /pv command, but that is not desirable

I would also like to mention, this issue appears to have been referenced by #223 but nothing conclusive came of that thread.

**Comment by Hwiggy** [comment]
Was this legitimately fixed, or was it closed to emphasize your own usefulness in taking care of legitimate issues?

**Comment by mbax** [comment]
Reporting an issue experienced 3 major minecraft releases out of date?
![That's a paddlin'](http://i.imgur.com/VxZ3N.gif)

**Comment by kashike** [comment]
You won't get help for Minecraft 1.8.8 from me. :dancer:
