### ISSUE TITLE
PVs don't open for some players

### ISSUE THREAD

**Issue by Disorbs** [drtshock/PlayerVaults#272]
Like everyone has been complaining not sure if you guys gave them an answer because all i see is them
getting closed.

bunch of players can't open their PVs not sure why cant pinpoint it yet but here is one
that cant open their PV 2

error for one of them i found
https://hastebin.com/gutegiqiva.vbs

this is what is inside their PV 2
https://hastebin.com/xonulihoce.tex

PlayerVaults: 3.6.0
paper: #1095

**Comment by drtshock** [comment]
Update, should be fixed.
