### ISSUE TITLE
Issue with ItemData?? Enchanted Pickaxes getting unenchanted.

### ISSUE THREAD

**Issue by GatorMC** [drtshock/PlayerVaults#273]
Enchanted Pickaxe in PV before closing:
https://prnt.sc/fjkybf

It becomes unenchanted pickaxe after closing and reopening PV:
http://prntscr.com/fjkymv

Here is the error in console:
https://hastebin.com/iqefiticak.sql

Important notes:
I use the TokenEnchant plugin which changes the Display name for enchants from for example: "efficiency.level.100" to "Efficiency 100". I contacted the dev for TokenEnchant about this problem and he said the problem is on PlayerVault's end. Please fix this if you can, thank you.

**Comment by drtshock** [comment]
Added support for this in latest update.
