### ISSUE TITLE
[High priority] Glitch with utf8mb4 and item data.

### ISSUE THREAD

**Issue by voodootje0** [drtshock/PlayerVaults#279]
There is currently a bug that you cannot open playervaults.
I start to investigate and saw the reason why the playervault couldn't be opened.

I found this in the playervault data.

>     '30': !!binary |-
>eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsImRhbWFnZSI6NDMsInR5cGUiOiJESUFNT05EX1NXT1JEIiwibWV0YSI6eyI9PSI6Ikl0ZW1NZXRhIiwibWV0YS10eXBlIjoiVU5TUEVDSUZJQyIsImVuY2hhbnRzIjp7IkRVUkFCSUxJVFkiOjMsIktOT0NLQkFDSyI6MiwiTE9PVF9CT05VU19NT0JTIjozLCJEQU1BR0VfQUxMIjo1LCJEQU1BR0VfVU5ERUFEIjo1LCJGSVJFX0FTUEVDVCI6MiwiREFNQUdFX0FSVEhST1BPRFMiOjV9LCJsb3JlIjpbIsKnNkxpZmUgU3RlYWwgSUlJIiwiwqdhSGVhZGxlc3MgSUlJIiwiwqc2U2hvY2sgSUlJIiwiwqc2R2xvcnkgSUkiLCLCpzZJbnF1aXNpdGl2ZSBJSUkiLCLCpzZEaXNhcm1vciBJIiwiwqdlRmFzdCBUdXJuIFYiLCLCp2VWYW1waXJlIFYiLCLCp2VSYWdlIFYiXSwiZGlzcGxheS1uYW1lIjoiwqdy4pq977iP8J+PuSDCp2JTcG9ydHPCpzRNYW7wn4+T8J+PgCJ9fQ==

I decode it with base64 and this returned.
>{"==":"org.bukkit.inventory.ItemStack","damage":43,"type":"DIAMOND_SWORD","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"DURABILITY":3,"KNOCKBACK":2,"LOOT_BONUS_MOBS":3,"DAMAGE_ALL":5,"DAMAGE_UNDEAD":5,"FIRE_ASPECT":2,"DAMAGE_ARTHROPODS":5},"lore":["§6Life Steal III","§aHeadless III","§6Shock III","§6Glory II","§6Inquisitive III","§6Disarmor I","§eFast Turn V","§eVampire V","§eRage V"],"display-name":"§r⚽️🏹 §bSports§4Man🏓🏀"}}

So when people are using emojis and other unsupported unicode characters the whole playervault cannot be opened anymore.

Could this be fixed asap?

**Comment by voodootje0** [comment]
I'm tagging some top contributors since in my opinion it's a huge bug.
@davismariotti @drtshock @kashike @turt2live @mbax  @evilmidget38 @vemacs @Terrobility @Byteflux

**Comment by turt2live** [comment]
Please don't ping everyone you see in a contributors list. Some of us haven't seen this repository in many years and won't be able to begin investigating the issue.

For your specific issue, it is not a critical bug. Yes, it's super annoying that vaults can't be opened, but it doesn't warrant the need to ping several people so soon. If it was a critical bug, then a responsible disclosure process should be followed instead.

**Comment by mbax** [comment]
I don't do Bukkit plugins since the DMCA takedown.

**Comment by kashike** [comment]
-.-

**Comment by drtshock** [comment]
That wasn't playervaults causing that.
