### ISSUE TITLE
Permissions not working.

### ISSUE THREAD

**Issue by VauxMC** [drtshock/PlayerVaults#280]
Players are unable to use the Vaults, they get the "You don't have permission for that!"
I use Spigot 1.10.2 and GroupManager for permissions.
The permissions I gave them.
    - playervaults.amount.1
    - playervaults.size.1
    - playervaults.commands.use

**Comment by blha303** [comment]
I'd suggest using a plugin like PermissionsEx, groupmanager is unsupported with all drtshock plugins because it's broken haha
