### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by TheRazerEyes** [drtshock/PlayerVaults#285]
People keep duplicing items by getting stuck in lilypad or trapdoor and then opening pv and putting it into their inventory and it duplicates it.

**Comment by contra1337** [comment]
Basically any time you can move with the inventory open you can dupe. it works with pistons, shulker boxes, ender pearls, etc.

**Comment by surgetheurge** [comment]
this isn't fixed is it?
same applies for freecam. 
you can move with hacked client free cam and dupe the pv inventory.

**Comment by contra1337** [comment]
I completely removed the backpack related code and compiled it, and I don't have the issue anymore. maybe a fix

**Comment by drtshock** [comment]
Does this still work? Can someone explain to me how you reproduce it?

**Comment by drtshock** [comment]
Please open the ticket with steps to reproduce and the version if you can.
