### ISSUE TITLE
My server won't have Playervaults plugin work

### ISSUE THREAD

**Issue by Viperfish1** [drtshock/PlayerVaults#286]
10.08 17:52:43 [Server] INFO at com.drtshock.playervaults.PlayerVaults.<init>(PlayerVaults.java:58) ~[?:?]

How do you fix tihs?

**Comment by Viperfish1** [comment]
YOU CLOSED THIS? WHAT KIND OF SUPPORT ARE YOU?

**Comment by LaxWasHere** [comment]
Have you tried turning it off and on again?
