### ISSUE TITLE
Crate Keys don't work with playervaults.

### ISSUE THREAD

**Issue by fireman1x** [drtshock/PlayerVaults#288]
I'm a developer for a small server, and on our server, whenever we put CrazyCrates Crate Keys inside a PV, and close it, when we open it again the enchantment, name, and lore is gone. 

I believe this is on Player Vaults' end because the default enderchest works with these items and there was a similar issue on this tracker recently, but was closed without answer.

Our server runs 1.11.2, and I'm unsure if there are 1.12 builds for this plugin yet so it would be greatly appreciated if there was an update for the 1.11.2 version.

**Comment by Mxra** [comment]
You could try adding your key ID(s) to the `blocked-items` list.
For example, if you use tripwire hooks as your keys:
```
blocked-items:
  - 131
```

**Comment by drtshock** [comment]
Playervaults doesn't support custom items at this time. It will in the future though :)

**Comment by drtshock** [comment]
Works in latest update :D
