### ISSUE TITLE
ConcurrentModificationException - deserialize Error

### ISSUE THREAD

**Issue by TerraPrimal** [drtshock/PlayerVaults#291]
Hi,

This issue reported back in 2016 (Issue #227 ) is still an issue today.
Some times with the ItemFlags metadata are causing vaults to not load.

I have added below the error along with a vault item that causes this error. Remove the ItemFlags meta manually from the item does allow the vault to load.

Error: https://pastebin.com/SF20nerJ
Vault Item: https://pastebin.com/74re3Ruj

Thanks.

**Comment by TerraPrimal** [comment]
Commenting out the following line seems fix the issue (ofc it needs a proper fix).
https://github.com/drtshock/PlayerVaults/blob/master/src/main/java/com/drtshock/playervaults/vaultmanagement/Serialization.java#L161

**Comment by drtshock** [comment]
Should be fixed in the latest dev build.
