### ISSUE TITLE
All PV's work except 1!

### ISSUE THREAD

**Issue by GibsonVS** [drtshock/PlayerVaults#294]
I have about 5000 Player Vaults saved and only 1 of them has an internal error and can't be opened. Here is the error.

https://pastebin.com/RPsYzvRR 

Also this is the player vault that is messed up. It's the players vault 1 that is having issues. They can open every other PV (2-3).

https://pastebin.com/jPB3H6NM

Thank you for your help!

**Comment by glisilghiro** [comment]
I have the same problem.

**Comment by drtshock** [comment]
Try updating to the latest dev build. Should be fixed.
