### ISSUE TITLE
Enchanted Items Bug

### ISSUE THREAD

**Issue by Downlqad** [drtshock/PlayerVaults#299]
ERROR Could not call method 'public static org.bukkit.inventory.meta.ItemMeta org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem$SerializableMeta.deserialize(java.util.Map) throws java.lang.Throwable' of class org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem$SerializableMeta for deserialization

**Comment by drtshock** [comment]
Fixed in new dev build.
