### ISSUE TITLE
Travis-CI builds are not active

### ISSUE THREAD

**Issue by DoNotSpamPls** [drtshock/PlayerVaults#301]
@drtshock

**Comment by drtshock** [comment]
back up

**Comment by DoNotSpamPls** [comment]
Are you sure about that 👀 
https://bitcoin.is-serious.business/8de494.png

**Comment by drtshock** [comment]
Sorry.  Ci is back up. I don’t use Travis for this project. I’ll remove it.

**Comment by DoNotSpamPls** [comment]
Okay, thanks!
