### ISSUE TITLE
Jenkins is down

### ISSUE THREAD

**Issue by Mxra** [drtshock/PlayerVaults#306]
Currently your Jenkins build server is down so I cannot download the version of this plugin that has the duping glitch(es) fixed. Could you add it to https://ci.akpmakes.tech/ as well?

**Comment by drtshock** [comment]
Yeah I'll see about getting it on there.

**Comment by Mxra** [comment]
Sounds good, thank you Trent.

**Comment by Mxra** [comment]
@drtshock Perhaps you could use the "Releases" feature here on GitHub in the meantime?

**Comment by drtshock** [comment]
Latest build is on spigot. I’ll hve Jenkins up ASAP.
