### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by houmapple** [drtshock/PlayerVaults#309]
Whenever a player takes something from the creative GUI, takes or puts something in PV, I get this error in console. Pastebin: https://pastebin.com/JECKvsak

**Comment by DoNotSpamPls** [comment]
@houmapple hello there! 
I see that you're using version 3.5.7, which is not the latest one. You can get the latest [here](https://www.spigotmc.org/resources/playervaultsx.51204/) (you can pay for it or compile the source code found in this repository for free, if you know how to do that)
If there is still an issue, please send your server version (you can get that by typing /version) and your plugin list (you can get that by typing /plugins)
