### ISSUE TITLE
signs not working

### ISSUE THREAD

**Issue by phyre** [drtshock/PlayerVaults#31]
I'm running a spigot-1.7.5-R0.1-SNAPSHOT
V3.5.0 of PlayerVaults. 

I'm getting the following error when trying to use a playervault sign:

http://pastebin.com/usuKfDxQ

Everyone has the appropriate permissions, - not sure what the issue is :/

**Comment by drtshock** [comment]
Fixed it :) https://github.com/drtshock/PlayerVaults/commit/8375d71e3ee43083f94f79d80c6751f2c021ec3a
