### ISSUE TITLE
blocked-items bypass.

### ISSUE THREAD

**Issue by LaxWasHere** [drtshock/PlayerVaults#310]
Player can bypass blocked-items by clicking on the item and dragging it in manually into the vault. Shift clicking an item works just fine (Being blocked).

**Comment by DoNotSpamPls** [comment]
Also, if you put an item in there, you can't get it out anymore.

**Comment by drtshock** [comment]
Can you give me the exact steps to reproduce? Lax's initial message there is a little confusing / could be taken the wrong way.

**Comment by DoNotSpamPls** [comment]
1. Block an item (for example a tripwire hook, preferrably if it's something with NBT tags, such as a spawner)
2. Put the item in a vault
3. You can put it in, but can't get it out.

**Comment by LaxWasHere** [comment]
Fixed
