### ISSUE TITLE
Bug duplication with items

### ISSUE THREAD

**Issue by NoopyyGaming** [drtshock/PlayerVaults#320]
Hey author,

i found a bug that my players use to duplicate their items. When they break a block, the block become invisible and they only need to go on the block and do the command for open the vault and take their items and do it again, so that's why they can duplicate items

**Comment by drtshock** [comment]
Which version of spigot and which version of playervaults? Please don’t say latest. Give me the output of /version and /version playervaults

**Comment by NoopyyGaming** [comment]
Okey, here you go :

![verssion plugin](https://user-images.githubusercontent.com/33123515/34604516-73c7fa4a-f208-11e7-8cb3-d1fcf9a4f7b7.PNG)
![version serv](https://user-images.githubusercontent.com/33123515/34604517-73f291ba-f208-11e7-9ea2-f2f819dc3362.PNG)

**Comment by Flavourized** [comment]
3.5.7 is the version with dupe bugs.


This is the new version of the plugin, which patches these issues:

https://www.spigotmc.org/resources/playervaultsx.51204/

**Comment by NoopyyGaming** [comment]
Nice but i can't buy it actually

**Comment by Flavourized** [comment]
@drtshock was nice enough to provide the source for the plugin. You can compile it yourself

**Comment by NoopyyGaming** [comment]
Why do i need to compile it ? i only want to install it on my server to fix the bug dupe because my players dupe item

**Comment by Flavourized** [comment]
You need to compile it to get the jar, which doesn't have the dupe bug, to install it on your server

**Comment by NoopyyGaming** [comment]
And i compile it with winrar or eclipse ?

**Comment by drtshock** [comment]
3.5.7 is an old version. It’s fixed as far as I’m aware on playervaultsx which starts with version 4.0

**Comment by NoopyyGaming** [comment]
Okey, and when can we download it ?

**Comment by drtshock** [comment]
It’s on spigot as playervaultsx
