### ISSUE TITLE
Duping bug,

### ISSUE THREAD

**Issue by ConradHD1** [drtshock/PlayerVaults#321]
PlayerVaultsX version (run `/version playervaults`): 4.0.1

Server software (run `/version`): Paperspigot 1.8.8

Server (`logs/latest.log`):

Details: https://www.youtube.com/watch?v=8Aa4PqFy56w

**Comment by ConradHD1** [comment]
This is an example video i found on a fork version to explain a method: https://www.spigotmc.org/resources/playervaults-updated.48374/updates 

But this still works on PlayervaultsX

**Comment by drtshock** [comment]
That’s a very old version of playervaults.

**Comment by ConradHD1** [comment]
It was just an example video on how to do it, i've managed to make the dupe work on 4.0.1 of playervaultsX

**Comment by Flavourized** [comment]
Make a video and post it here :D

**Comment by drtshock** [comment]
Show a video on playervaultsx then.

**Comment by drtshock** [comment]
Closing this so people don't freak out about something that isn't confirmed. 

@ConradHD1 please re open once if you can post proof that this works on PlayerVaultsX and I'll make sure to fix it ASAP.
