### ISSUE TITLE
PlayerVaultsX 4.0.1 bugs. 

### ISSUE THREAD

**Issue by LiviDk** [drtshock/PlayerVaults#328]
PlayerVaultsX version (run `/version playervaults`): 
4.0.1

Server software (run `/version`): 
Spigot 1.8.8 (kitpvp server)

Server (`logs/latest.log`):
https://gist.github.com/LiviDk/9180f0ada285fbfc286e7fc6ee12263e

Details:
I made a video about it, because i don't know how to describe it. But let's try:
If player A puts stuff in his /pv, and player B tries to take it out, then player B is able to continue pulling the item(s) out of player A's /pv, and player A won't loose his stuff in his /pv.
https://www.youtube.com/watch?v=72GTxtmH4Lg&feature=youtu.be

**Comment by drtshock** [comment]
Keep in mind this only affects admins viewing users vaults which is why I haven’t deemed this critical. Nevertheless, I’ll get it fixed ASAP.

**Comment by DoNotSpamPls** [comment]
uhh, bump?

**Comment by drtshock** [comment]
Fixed in https://github.com/drtshock/PlayerVaults/commit/b1033c77ade13f36c5f17cab5eeeef6395f5741b
