### ISSUE TITLE
Failed to convert vaults from UUID > B64

### ISSUE THREAD

**Issue by LaxWasHere** [drtshock/PlayerVaults#329]
Server log: https://hasteb.in/akurezizuc.tex
UUID.yml: https://hasteb.in/uxetitoyom.md

/pv 1 from PlayerVaults v3.6.0-bSNAPSHOT:  https://pastebin.com/d1jgEETn

Should help convert messed up uuid.ymls to b64.

**Comment by drtshock** [comment]
Fixed
