### ISSUE TITLE
Conversion

### ISSUE THREAD

**Issue by glisilghiro** [drtshock/PlayerVaults#331]
PlayerVaultsX version PlayerVaultsX 4.0.1

Server software Paper version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Server (`logs/latest.log`): https://hastebin.com/tapabapike.md

Details: https://hastebin.com/dutefozubo.vbs When I start server It generate this error and not convert vaults
now I send you all log if necessary

**Comment by drtshock** [comment]
I'll try to take a look at this asap.

Can you give me your spigot username?

**Comment by glisilghiro** [comment]
xscorpion93x

**Comment by drtshock** [comment]
Thanks, just wanted to verify that you did purchase. I will take a look at this asap :D

**Comment by glisilghiro** [comment]
news?

**Comment by drtshock** [comment]
Fixed in latest release.
