### ISSUE TITLE
"Cannot into itemstacksz"

### ISSUE THREAD

**Issue by MinecraftAdmin** [drtshock/PlayerVaults#332]
PlayerVaultsX version (run `/version playervaults`): 
4.0.1
Server software (run `/version`): 
Paper git-Paper-1320 (MC: 1.12.2)
Server (`logs/latest.log`):
https://pastebin.com/raw/eLVH1k86
Details:
Error when converting from PlayerVaults to PlayerVaultsX

Spigot name "MinecraftAdmin" for verification.

**Comment by MinecraftAdmin** [comment]
Spigot name "MinecraftAdmin" for verification.

**Comment by MinecraftAdmin** [comment]
I accidentally reported the "/version playervaults" from my live server (which was reverted back to the old version), the actual version in use is PlayerVaultsX 4.0.1

**Comment by KugelblitzNinja** [comment]
I had this same issue.  Same Paper version.
After updating Paper Spigot from https://yivesmirror.com/downloads/paperspigot this issue just stopped.

Using Paper git-Paper-1321 (MC: 1.12.2) and PlayerVaults 4.0.1
