### ISSUE TITLE
[Feature Request] use player's name instead of uuid in saving vault's info

### ISSUE THREAD

**Issue by iedesu** [drtshock/PlayerVaults#333]
PlayerVaultsX version (run `/version playervaults`): 
latest (4.0.1)
Server software (run `/version`): 
spigot 1.5.2
Server (`logs/latest.log`):
maybe nope
Details:
because i am still on 1.5.2, and most of the plugins in this version save data with
player's name, not player's uuid
so, configuration that switchs file name saving method of vault could be added?

i know my server is so outdated,
but there was "Should work on any Minecraft version." in spigot page
so i am requesting this :p

thanks

**Comment by drtshock** [comment]
Eh probably not lol. Does 1.5.2 not have player uuids?

**Comment by iedesu** [comment]
nope but most plugins in 1.5.2 uses playername
so it's quite incompatible i think

**Comment by GiansCode** [comment]
The addition of UUIDs was introduced in Minecraft 1.7.5 (which released February 26, 2014), if I recall.

Is there any particular reason you're on an incredibly old version of the game?

**Comment by Flavourized** [comment]
>  Is there any particular reason you're on an incredibly old version of the game?

He is a hipster, duh

>
