### ISSUE TITLE
Language Issue - Version 4.0.2

### ISSUE THREAD

**Issue by QualityNodeNet** [drtshock/PlayerVaults#336]
PlayerVaultsX version (run /version playervaults): PlayerVaults version 4.0.2-SNAPSHOT-QualityNode

Server software (run /version): CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) and Paper version git-TacoSpigot-"fe7806b0" (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (logs/latest.log): No Errors, are occurring at all, so no need.

Details: Loading Dutch Lang File, instead of lang.yml or english.yml
Config.yml: https://pastebin.com/wQNdpV0y
lang.yml https://pastebin.com/iFyarByw
english.yml: https://pastebin.com/3AT680Bz

**Comment by kashike** [comment]
no log file provided
