### ISSUE TITLE
Useless language file line

### ISSUE THREAD

**Issue by ArtelGG** [drtshock/PlayerVaults#339]
Just a little nitpicky, [this](https://github.com/drtshock/PlayerVaults/blob/master/src/main/resources/lang.yml#L11) shouldn't be in the language files anymore.

**Comment by kashike** [comment]
PRs are welcome.

**Comment by Mxra** [comment]
Not too good with external other peoples' git repos, I only do my own on GitLab, plus I don't want to mess anything up by accident.

**Comment by ArtelGG** [comment]
Update: Made a PR.
