### ISSUE TITLE
Vaults erroneously transferring between players and staff

### ISSUE THREAD

**Issue by MinecraftAdmin** [drtshock/PlayerVaults#34]
Player 1 asks Player 2 to check their vault using /pv player1 1
Player 2 types /pv player1 1
Player 2 closes the inventory GUI
Player 2 types /pv 1
Player 1's vault no. 1 inventory has been transferred to Player 2's vault no. 1

This has resulted in a few of my players vaults simply disappearing.

Vault files after the error has occured. Notice that Player 2's Vault no. 1 is exactly the same as Player 1's Vault no. 1

Player 1's vault file: http://pastebin.com/raw.php?i=WWe35h3z
Player 2's vault file: http://pastebin.com/raw.php?i=Unc3qXJj

**Comment by drtshock** [comment]
I haven't seen any instances of this other then when behind a bungee proxy that might not be forwarding UUIDs right away. I have seen this run behind bungee successfully many times.
