### ISSUE TITLE
I don't know if you can help but need help giving players more vsults

### ISSUE THREAD

**Issue by grannypatty** [drtshock/PlayerVaults#341]
PlayerVaultsX version (run `/version playervaults`): 
 Urgent
Server software (run `/version`): 

Server (`logs/latest.log`):

Details:
We offer pvp for sale in our buycraft store but it won't let us add them, we have to do it manually 
We have a player that bought 18. We are trying 
/pex user [name] add add.playervault.add 18 
But it's not working
Can it be done ingame or does it have to be on console and is the command line correct?

**Comment by ArtelGG** [comment]
You're adding the wrong permission.

**Comment by drtshock** [comment]
Urgent isn't a version.

`playervaults.amount.1` is the permission to give them 1 vault. Did you not read the permissions on the project page? :(
