### ISSUE TITLE
Issue with sending two responses

### ISSUE THREAD

**Issue by ArtelGG** [drtshock/PlayerVaults#343]
**PlayerVaultsX version:** Latest changes from this Git repository.
**Server software:** TacoSpigot 1.8.8-b29
**Server:** N/A
**Details:** It sends both the integer and player response.
![screenshot_1](https://user-images.githubusercontent.com/21347579/37670770-8ee76f00-2c40-11e8-9e9d-82fbec570af9.png)

I might make a PR later, however, I'm quite tired right now and don't really have the motivation to do so.

**Comment by drtshock** [comment]
Hm, just a missing return statement I'm thinking. Obviously isn't a critical issue, just annoying. I'll take a look at it.

**Comment by ArtelGG** [comment]
Yeah, that's what I figured as well.

**Comment by drtshock** [comment]
Eh this would only happen for admins. Is it necessarily bad that it shows you both that it couldn't find a vault OR a player for that?

**Comment by ArtelGG** [comment]
I feel like there'd be a better way to go about it, such as searching for the username and if it isn't online then it tries to parse it as only an integer. Obviously only do that if they have permission to open others' vaults, if not just go straight to integer parsing.

**Comment by drtshock** [comment]
Should be fixed now.
