### ISSUE TITLE
Let other players access your own vault

### ISSUE THREAD

**Issue by i9hdkill** [drtshock/PlayerVaults#35]
Hi,
I wanna use this great plugin to create a guild vault.
Giving the guildleader the vault permissions.
He can add players to his vault so that they can access his vault.

Could you implentant that? Could be a bit tricky to avoid duplication?!

Tanks!:)

**Comment by drtshock** [comment]
While I won't do it like this, we can look into having Faction vaults.

**Comment by i9hdkill** [comment]
Yeah, or simple clans 2 Vaults. I was thinking basically the same think. Just don't know if it's possible with their api.

**Comment by conetopia** [comment]
I would love an actual Guilds Plugin that involves Vaults and passworded chests
with Rogue classes that have a chance to open the chest or die.
