### ISSUE TITLE
Issue with blocking a player's vault opening

### ISSUE THREAD

**Issue by GwnDaan** [drtshock/PlayerVaults#354]
Hey,

Some people messaged me about my plugin conflicting with yours. Now I took a look in your code and you put people in the list of being in the vault without checking if they've successfully opened their inventory. So what you should do, I've not tested it though, is checking with `player.getOpenInventory() != null` after you've opened their inventory. That way other plugins can cancel the InventoryOpenEvent called when the inventory is opened by your plugin. In the meantime I've made a commandblocker for my plugin so this shouldn't be an issue anymore, but to prevent other plugins conflicting with yours, you should add something to check if the inventory has successfully openend, and if not don't let the code think the player is in the vault when he is not.

**Comment by EvilSlime** [comment]
I have the same issue.

**Comment by GwnDaan** [comment]
> So other plugins are blocking mine from opening? Can you give me an example of when and why?

`	@EventHandler
	public void onOpen(InventoryOpenEvent event) {
		Player player = (Player) event.getPlayer();
		User user = UserManager.getInstance().getUser(player);
		if (user == null) return;
		event.setCancelled(true);
		player.sendMessage(MessageManager.CANNOT_DO_THAT.getValue());
	}`

Whenever they try to open the pv, it'll get cancelled by my plugin because they may not use it at that point. 

So I think you should check if the inventory has successfully opened by checking it with `player.getOpenInventory() != null` everytime you have opened a inventory. This may not work as I have not tested it.

**Comment by drtshock** [comment]
Let me know if that fixed it.
