### ISSUE TITLE
Charging Double for /pv creation?

### ISSUE THREAD

**Issue by DatNubTriz** [drtshock/PlayerVaults#358]
PlayerVaultsX version (run `/version playervaults`): 3.5.7-b${BUILD_NUMBER}

Server software (run `/version`):  git-Spigot-2086bb0-8cc5a7e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Server (`logs/latest.log`):

Details: I have the cost-to-create a /pv set to $100,000 yet any time someone creates one, it will charge them $20,000? I've edited and saved the config.yml dozens of times and used /pvreload and also rebooted the server a few times also and still no change?

**Comment by LaxWasHere** [comment]
Support for your version has been dropped. Please update.
