### ISSUE TITLE
VaultsX Bug [Premium]

### ISSUE THREAD

**Issue by iTommyB** [drtshock/PlayerVaults#359]
PlayerVaultsX version (run `/version playervaults`): 
http://totally-not.a-sketchy.site/f427e3.png - Picture of playervaults version.

Server software (run `/version`): 
http://totally-not.a-sketchy.site/d7c37a.png - Picture of server version

Server (`logs/latest.log`):
http://www.mediafire.com/file/522k7zcxw1r1tsq/latest.log/file - latest.log obviously

Details:
https://www.youtube.com/watch?v=LD23hbnLGEI - Video showing the bug
https://hastebin.com/pezuwediki.vbs - Error from console
http://www.mediafire.com/file/mmjnfnxs3lavp8i/config.yml/file - Config just in case it's needed.

**Comment by drtshock** [comment]
Reopen if you can post updated links that don't expire.
