### ISSUE TITLE
Messages (lang) issue

### ISSUE THREAD

**Issue by TheRBZ** [drtshock/PlayerVaults#360]
PlayerVaultsX version (run `/version playervaults`): 4.0.5

Server software (run `/version`): Spigot 2086bb0-d0a3620 1.12.2

Server (`logs/latest.log`):

Details:
In the PVX english.yml, I've set the title-name to "" to remove the prefix but it leaves a one space gap from where the message starts to the text content. This is annoying because I don't want prefixes but it leaves an annoying gap.

![image](https://user-images.githubusercontent.com/39860014/40878054-2e2aac86-6683-11e8-9465-fd3505088b2b.png)

**Comment by ArtelGG** [comment]
So, you removed the prefix only to add another one to each individual message? Why?

**Comment by CmdrKittens** [comment]
Coming soon to 4.1.7
