### ISSUE TITLE
Alternos

### ISSUE THREAD

**Issue by ohJoeyLies** [drtshock/PlayerVaults#362]
PlayerVaultsX version (run `/version playervaults`): 3.5.7

Server software (run `/version`): git-Bukkit-fbe3046

Server (`logs/latest.log`):

Details: I will try to make this make sense, but I'm tired. I'm using the free website, aternos, to host a server. It's not that big of a deal but I wanted to use playervaults. I added it to the server via the "Plugins" button built into the website. It wasn't until I was on the server with some friends that I realized: they couldn't use playervaults unless they were opped, and I don't want to op them. I went to aternos to change permissions (yes i read the project page) but I could not find a permissions file. I think it exists but I do not have access to it and I am wondering what I could do about it? I'm not entirely sure as this is not hosted on my computer because it is a free website. Any help would be appreciated. =)

**Comment by DoNotSpamPls** [comment]
You need a permissions plugin such as LuckPerms or PermissionsEx (now abandoned). However, I wouldn't recommend you investing too much time setting up permissions for a free server - it just isn't worth it.
