### ISSUE TITLE
playervaults.commands.use is useless?

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#363]
In your playervaultsx plugin.yml you got:
```
playervaults.commands.use:
    description: Open own vault with command.
    default: true
```
But I notice that permission is not required for players to use vaults if they just have playervaults.amount.<number>

Is this Intended?

(Meaning if specifically set to default: false, or permissions plugin is in this case ignoring bukkit defaults, the above permissions is still useless)

Example: A user can have playervaults.commands.use: false and playervaults.amount.1: true, and they can do /pv 1 and use the vault perfectly fine.

**Comment by andrewkm** [comment]
@drtshock Wondering if you can take a peak at this and let me know.

**Comment by drtshock** [comment]
You're correct.
