### ISSUE TITLE
Sign message not formatted when clicking it

### ISSUE THREAD

**Issue by AKATONYEXILE** [drtshock/PlayerVaults#365]
PlayerVaultsX version (run `/version playervaults`): **4.0.5**

Server software (run `/version`): This server is running **CraftBukkit version git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

Details: **The sign message "&fOpening vault &a%v &fof &a%p" doesn´t have a entry in the language file.**
![vaultmes](https://user-images.githubusercontent.com/28605608/42185581-b2549e12-7e49-11e8-889b-5e5607a35743.PNG)
![vaultmes2](https://user-images.githubusercontent.com/28605608/42185582-b27a521a-7e49-11e8-8241-ed07bbf51247.PNG)

**Comment by drtshock** [comment]
Should be fixed in 4.1.0
