### ISSUE TITLE
PlayerVaults Reorganization Issue

### ISSUE THREAD

**Issue by Apyrax** [drtshock/PlayerVaults#366]
PlayerVaultsX version (run `/version playervaults`): PlayerVaults Version 4.0.5

Server software (run `/version`): This server is running CraftBukkit version git-PaperSpigot-"8b18730"(MC:1.8.8) (Implementing API Version 1.8.8-RO.1-SNAPSHOT)

Server (`logs/latest.log`): I do not have any latest logs as I only just wiped them all a bit ago. 

Details: Recently, some of my users have been having issues with their items being moved around in PlayerVaults, now this only happens with player vaults having under 4 rows. I've tested it and it does what they reported. I've linked a gyazo down below 

https://gyazo.com/e8f72711f46f70ed54858c0de165532e

**Comment by Apyrax** [comment]
drtshock?

**Comment by drtshock** [comment]
Thanks for the info on that it only happens for smaller vaults, helped me narrow it down once I finally had time to work on int. Fixed in that commit and the 4.0.7 release.
