### ISSUE TITLE
Not really an issue, asking before I buy ....

### ISSUE THREAD

**Issue by hal2k2** [drtshock/PlayerVaults#369]
PlayerVaultsX version (run `/version playervaults`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Hello as I said question before I buy...
I see a recent update "Last Update:
    Aug 8, 2018"
Was that to 1.13 by any chance, looks like a good personal vault system !

Thanks in advance for a prompt reply

hal2k2

**Comment by drtshock** [comment]
Yes it works on 1.13
