### ISSUE TITLE
Different vault size for different vault chest

### ISSUE THREAD

**Issue by madtomic** [drtshock/PlayerVaults#370]
Can you you add separate size for each vault chest?

vault sizes
pv 1 is size 6 slots
pv 2 is size 2 slots

**Comment by Nedjii** [comment]
+1

**Comment by madtomic** [comment]
Any news on this feature request?

**Comment by drtshock** [comment]
no news

**Comment by triesharder** [comment]
Would be very cool if players were able to upgrade their vaults with currency or certain tokens.

limited by permissions like
`playervaults.upgrade.maxSize.<size>`

**Comment by mbax** [comment]
Doable in 5.0, currently in alpha testing.
