### ISSUE TITLE
Feature request, Disable per world

### ISSUE THREAD

**Issue by yummiesttag** [drtshock/PlayerVaults#371]
PlayerVaultsX version (run `/version playervaults`): 

Server software (run `/version`): 

Server (`logs/latest.log`):

Details: it would be nice if you could disable PV in certain worlds like a creative plots world, I know you can disable the permission but I have 100 ranks and adding that for every rank won’t be fun.

**Comment by drtshock** [comment]
Just disable access to the command via your permissions plugin in that world.
