### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by RogerPlaysMC** [drtshock/PlayerVaults#376]
If my players have low ping (>1000ms) they can run /pv 1 multiple times before the inventory opens. Then when they remove items and close the inventory the items are both in their inventory and back in the vault. We had one player who started with 1 spawner dupe 5 stacks in a couple minutes. 

I read this was an issue with another vault plugin a while back. Essentially it was leaving multiple open inventories, and it’s not saving the most up to date one. The fix was to first run a line to close the players open inventories , then open the new inventory. Running 1.8.8 BeerSpigot.

**Comment by RogerPlaysMC** [comment]
The player has agreed to show me how he did it, hopefully I can post more info tomorrow night.

**Comment by drtshock** [comment]
Which version of PV are you on here? This shouldn't be an issue as we check once they type /pv if they are trying to type it again.

**Comment by RogerPlaysMC** [comment]
The player was unable to replicate when recording, and I was not able to replicate. If anything changes I’ll let you know, but I’ll close it for now.
