### ISSUE TITLE
pvdel all echoes message saying it worked.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#378]
Using /pvdel player all
Echoes the following message:

https://i.imgur.com/mFY1W6a.png

Making it seem like the command worked, even though user has no permissions.

Furthermore, the playervaults.* or playervaults.admin or any permission for that matter, doesn't seem to grant the pvdel player all permission.

The pvdel player all system simply doesn't work for some reason.

**Comment by drtshock** [comment]
Thanks for pointing out. Can you give more info on the permissions issue?

**Comment by andrewkm** [comment]
My issue is quite clear...
Did you just close an issue which is a valid bug? Lol....

**Comment by andrewkm** [comment]
@drtshock oh I see, you closed this with a commit.

I was looking at this last night just before bed all like wtf ? xD

The permissions issue, is that the command doesn’t actually work? Meaning no vaults are cleared ever.
