### ISSUE TITLE
Translation issue when you open vault via sign

### ISSUE THREAD

**Issue by xion87** [drtshock/PlayerVaults#381]
### PlayerVaultsX Version
*Run `/version playervaults` and give us your output.* 
4.1.0

### Server Version
*Run `/version` and give us your output.*
Paperspigot 1.8.9

### Logs
*Give use your logs by going to `logs/latest.log`.*
No Necessary

### Details
*Please explain the problem.*
When i open the vault via sign, it use the default english message, instead to use "open-vault" string message

**Comment by drtshock** [comment]
Can you show the screenshot? There aren't any places we send non localized messages that I see.

**Comment by xion87** [comment]
![image](https://user-images.githubusercontent.com/3611852/54879644-99177880-4e3b-11e9-9cd0-eb30dc24fa19.png)

english.yml (i translated some thing in italian)
![image](https://user-images.githubusercontent.com/3611852/54879668-e267c800-4e3b-11e9-8f81-3048abfbe593.png)

**Comment by drtshock** [comment]
Are other translated messages working correctly? Because it appears to be pulling from just the translations file.

**Comment by xion87** [comment]
yep, just that is missing

**Comment by CmdrKittens** [comment]
This items were missing from our defaults:

```
vault-does-not-exist: "&cThat vault does not exist!"
click-a-sign: "&fNow click a sign!"
not-a-sign: "&cYou must click a sign!"
set-sign-success: "&fYou have successfully set a PlayerVault access sign!"
open-with-sign: "&fOpening vault &a%v &fof &a%p"
```

They will be added to each language (untranslated, waiting on translation PR) for the next release.
