### ISSUE TITLE
NBT Tags not working

### ISSUE THREAD

**Issue by StarhunterUC** [drtshock/PlayerVaults#383]
I use PlayerVaultsX for minecraft 1.7.10 (Modded)

These modded items are guns that can hold attachments but when a gun is placed inside any PV the attachment will clear (The items are NBT Tags on the gun)

**Comment by drtshock** [comment]
Can you show me your full server logs as well as how the NBT tags are being created? Ideally linking to the plugin / mod in question's source.

**Comment by StarhunterUC** [comment]
source for the mod is private, but they save itemstacks into the item nbt for different attachments

(Is what i was told)

**Comment by drtshock** [comment]
Ok well I'll need some info to go on like logs or the jar then..

**Comment by StarhunterUC** [comment]
Nothing shows up in the logs but i can get you the mod JAR

https://minecraft.curseforge.com/projects/decimation-zombie-apocalypse/files/2704480

**Comment by CmdrKittens** [comment]
Wipes should no longer happen. Items that are incompatible with Bukkit's item saving system will not be able to be put in vaults.

If you continue to have trouble on 4.1.6 and beyond please open a new ticket :)
