### ISSUE TITLE
[Request] Force openening vault

### ISSUE THREAD

**Issue by SirKillian** [drtshock/PlayerVaults#384]
### Idea
A force open admin/console command.

The reason why I think this is a good idea is because I basically want to replace enderchests with the playervaults. kinda like the current signs feature, but then with echest.

So basically whenever a player tries to open an enderchest I can cancel the event and make it execute the force open command through console. The only issue right now is that player can still use /pv and open the vault from any location.

### Details
This would be a specific command only usable to those with the correct permission node and/or executable from console.

This will make it possible for admins and/or console to force open a specific playervault for a player without having the "/pv #" command and/or vault signs enabled.

**Comment by mbax** [comment]
pvconsole command implemented somewhere in version 4.3.x
