### ISSUE TITLE
[BUG] Player's vault clear because of cashnote plugin items

### ISSUE THREAD

**Issue by BoBsmil3Y** [drtshock/PlayerVaults#385]
Hey there, 

I'm actually using PlayerVault's X 4.1.2 with 1.13.2 Paper Spigot and I found a bug with the plugin "Beast-WithDraw". Player use this plugin to convert money into paper of X$ (cashnote) and to convert xp into one bottle of X xp.

When a player put a cashnote into his pv, after quit and join his pv get clear. This is the error : 

https://pastebin.com/LHvtenea

**Comment by ArtelGG** [comment]
I wasn't able to reproduce this with my withdrawal plugin, from what I can tell it's caused by the way the author handles his NBT.

**Comment by CmdrKittens** [comment]
I believe we have fixed this in the latest release.
