### ISSUE TITLE
Permissions to over 100 vaults blowing everything up.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#386]
**Evnironment**
Paper: 1.13.2 Build 626
PlayerVaults compiled on: https://github.com/drtshock/PlayerVaults/commit/8008663c1f7d99824d350311818ee3e05c767514 (One build behind).

Give player permission:
playervaults.amount.1 - correctly have access to /pv 1
playervaults.amount.10 - correctly have access to /pv 1 through /pv 10
playervaults.amount.99 - correctly have access to /pv 1 through /pv 99
playervaults.amount.100 - have access to only /pv 100 (/pv 1 through /pv 99 denied)
playervaults.amount.101 - have access to only /pv 101 (/pv 1 through /pv 100 denied)

**Comment by ArtelGG** [comment]
Could you tell me your permissions plugin?

**Comment by andrewkm** [comment]
We use LuckPerms.
And yes, we have people with 90+ vaults filled up ;)

**Comment by ArtelGG** [comment]
Do you not reset your server? That's the only time I can see 90+ full double chests being filled up. Perhaps it's an "OP" server?

**Comment by andrewkm** [comment]
The ins and outs of my server is irrelevant to the bug being discussed. It is in fact a bug. That should is the topic.

**Comment by drtshock** [comment]
Yes I'm aware of this and confirm it. I'll be fixing this + the other NBT issue soon. Thanks for your patience.

**Comment by andrewkm** [comment]
Any updates on this @drtshock

**Comment by CmdrKittens** [comment]
Added configuration item `max-vault-amount-perm-to-test` with default value of 99 (matching current setup). Can be modified to whatever value you like.

**Comment by andrewkm** [comment]
@CmdrKittens your latest commits do not compile, likely due to: https://github.com/drtshock/PlayerVaults/commit/876c696e86fd8933522cf4db31360b46cfbac037

https://pastebin.com/raw/p0H1LZ2P

**Comment by CmdrKittens** [comment]
@andrewkm It appears that Spigot 1.14 dropped org.json.simple from their API. It is still in the final compiled jar though, so I believe the plugin will work if you edit pom.xml line 56 to be 1.13 instead of 1.14 and build, even on 1.14 and 1.15

I will investigate further, but may or may not have the time today.

**Comment by andrewkm** [comment]
Confirmed compiling properly and bug tested/fixed. <3
