### ISSUE TITLE
Not resetting player vaults even if permissions are removed

### ISSUE THREAD

**Issue by lw9244** [drtshock/PlayerVaults#388]
### Idea
*Tell us what you want!*
Currently, the player vaults are wiped for slots that players don't have permission for if they lose the permission / regain it and open it. I'm just looking for the inventory to be persistent.

### Details
*Give some more information so we can get an idea.*
Player vault items should persist whether or not player has permission to them or not so if they regain permission for slots, they still retain the items.

**Comment by drtshock** [comment]
This is why you shouldn't lower the slots. I can implement something like this, it's just going to be a pretty big change since I'll have to store things as slots rather than just an inventory.

**Comment by triesharder** [comment]
This was also requested on #388.

I was looking issues before asking for somethig similar, would be easier to make the items be dropped in situations like that?

**Comment by mbax** [comment]
Resolved in 5.0, currently in alpha testing.
