### ISSUE TITLE
Adding PV's instead of setting

### ISSUE THREAD

**Issue by ThyV0001** [drtshock/PlayerVaults#392]
### Idea
*Make it a setting where you can add the amount of pv's a player can use via command, or permission, for example a normal rank would get 5, a detonator rank would get 10, in total they should have 15, not a set amount of 10 *

### Details
*Player 1 - Non donator, maxed rank, - 5 PVs
Player 2 - Donator, - 10 PV's
Player 3 Donator & maxed rank, - 15PV's
*

**Comment by drtshock** [comment]
Yeah this has been requested a few times. There's currently an addon that lets you do this written by a good friend https://www.spigotmc.org/resources/%EA%A7%81-%E2%96%AC%E2%96%AC%E2%96%AC%E2%98%85-playervaults-gui-%E2%98%85%E2%96%AC%E2%96%AC%E2%96%AC-%EA%A7%82.52057/

**Comment by mbax** [comment]
Doable with bundles in 5.0, currently in alpha testing.
