### ISSUE TITLE
Cant blacklist default shulker boxes from player vaults

### ISSUE THREAD

**Issue by JHarris12345** [drtshock/PlayerVaults#393]
### PlayerVaultsX Version
*Run `/version playervaults` and give us your output.* 
3.5.7-b${BUILD_NUMBER}

### Server Version
*Run `/version` and give us your output.*
Paper version git-paper-597 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://gist.github.com/JHarris12345/ee9d24f3528d49571d303394b741d76c

### Details
*Please explain the problem.*
When using the config feature to blacklist items from going in your PV, I can block spawners and shulker boxes by using LEGACY_MOB_SPAWNER and LEGACY_BLACK_SHULKER_BOX etc. It works for all of them except the default SHULKER_BOX which doesn't have a colour. I have tried SHULKER_BOX and LEGACY_SHULKER_BOX and none seem to work

**Comment by drtshock** [comment]
Can you try on playervaultsx? https://www.spigotmc.org/resources/playervaultsx.51204/

**Comment by CmdrKittens** [comment]
No response, closing.
