### ISSUE TITLE
[Idea Request] : Per world Playervaults

### ISSUE THREAD

**Issue by Chronic-Reflexes** [drtshock/PlayerVaults#399]
### Idea
The main idea was for servers that reset every X amount of months, but don't want to get rid of the map, and have old players in both the new and old maps, but people can bring items from last season into the new season map.

### Details
Ways you could go about executing this would be to add world groups

lets say you have 4 worlds (with their respective nether and ends) but only want connection between 2 of those worlds.  you would add world 1&2 to a world group. and world 3&4 to a different world group.

The result:
Players can seamlessly play between old and new maps, without creating the risk of bringing over unwanted items into new maps, while keeping functionality of playervaults, and setup for server owners relatively easy instead of having to mess with permissions

**Comment by TazMatic** [comment]
So this is a current limitation that I'm having as well and would love to have this feature

**Comment by mbax** [comment]
This will be doable with separate bundles tied to separate permission nodes (which could be granted per-world) in 5.0. Already resolved, just awaiting testing and release.
