### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by Host1229** [drtshock/PlayerVaults#401]
Hey guys. I recently came in contact with an issue on my modded minecraft server when I installed the player vaults plugin. I'm sure most of you are familiar with the plugin. In my modpack there are backpacks which you can put items into. When you put one of these backpacks with items in it into the vault, then reopen the vault, all the items in the backpack clear. If anyone has any ideas on how to fix this, please get back to me. Thank you so much.

**Comment by CmdrKittens** [comment]
Howdy! Try running on the latest release: https://www.spigotmc.org/resources/playervaultsx.51204/

If you continue to have difficulty, reach out on our discord!
