### ISSUE TITLE
I have multiple worlds using player vaults.

### ISSUE THREAD

**Issue by OneWetBoy** [drtshock/PlayerVaults#402]
### PlayerVaultsX Version
3.5.7

### Server Version
1.15.2

### Logs
[latest.log](https://github.com/drtshock/PlayerVaults/files/4453677/latest.log)

### Details
I have a few worlds that I want to have access to player vaults but they all combine. I have skyblock, survival, prison, and factions as worlds that I want t have permission to playervaults but when they type /pv the items from skyblock are still there even if they are in prison.

**Comment by mbax** [comment]
This will be doable with separate bundles tied to separate permission nodes (which could be granted per-world) in 5.0. Already resolved, just awaiting testing and release.
