### ISSUE TITLE
Allow users to rename their playervaults

### ISSUE THREAD

**Issue by iSneaky** [drtshock/PlayerVaults#404]
### Idea
Allow users to rename their playervaults

### Details
I'd like to see the idea of users being able to rename their vaults, for example, instead of typing "/pv 1" to open playervault 1, we could use "/pv food" which would open playervault 1 where the player primarily likes to store food. To rename a playervault, a command such as "pvname <pv#> <namehere> would be issued by the player.

This would be great for players who have lots of playervaults, like 50+, they could have each playervault named after 1 building material, instead of having to remember a random number that contains that material.

**Comment by andrewkm** [comment]
This would be great!
Make it happen @CmdrKittens <3 I give dollars. :)

**Comment by ChitterChatter** [comment]
This would be great, is this something that could maybe be considered?

**Comment by Tirco** [comment]
I also support this request.
In theory it's as simple as storing one extra field pr inventory, and making sure the rename cmd doesn't accept number names :)

**Comment by icarapovic** [comment]
This is also highly requested on the server I play on, can we get some feedback is the dev at least considering it?

**Comment by mbax** [comment]
There's a rework planned for 5.0, which would enable named vaults. I do want to see this happen.

**Comment by mbax** [comment]
Now tracking here, for 5.0 https://github.com/KittehDev/PlayerVaultsX/issues/3
