### ISSUE TITLE
Signs broken.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#405]
/pvsign 1
Click a sign.
Get message "You must click a sign!" https://i.imgur.com/yZtd2aH.png

Assuming not updated for new signs (oak_sign, blabla)
Compiled on: https://github.com/drtshock/PlayerVaults/commit/97d977b99638d5e43ffa0ffe50596e09614d878a
Using Paper build 165 (1.15.2)

**Comment by CmdrKittens** [comment]
Fun fact! For some strange reason it is expecting only *right clicks* on a sign. 

Unless I get a convincing reason not to do so, the next release will allow left clicking too.

**Comment by andrewkm** [comment]
Confirmed working :)
