### ISSUE TITLE
Major dupe bug.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#407]
Edit: Got it fixed in Paper, was far wider scale.

**Comment by andrewkm** [comment]
https://github.com/PaperMC/Paper/commit/8918245090255896ed0f59abea4274ec17f356a2
Not sure if you wanna address this on your end, but prior to this change, you can dupe in several ways while in a bed with playervaults. @CmdrKittens 

I'll keep it open for you.
Sorry for no detailed info previously, I woke up to dupes and explosions middle of the night :P

**Comment by mbax** [comment]
Hey andrew, I'm coordinating with folks to get this handled from the PV end as well. Made a few... minor... changes to the issue just to make it not show up in issue searches.

**Comment by CmdrKittens** [comment]
Version 4.1.8 includes catches for the problem, so this should work even for situations of outdated paper as long as 4.1.8 is running. Tested, too.
