### ISSUE TITLE
yml format

### ISSUE THREAD

**Issue by Aligayah** [drtshock/PlayerVaults#410]
### Idea
*Tell us what you want!*
I think it would be a good idea to change the config file type to yml.
This is because Multicraft doesn't show .conf files in the config viewer.

### Details
*Give some more information so we can get an idea.*

**Comment by CmdrKittens** [comment]
This sounds more like a flaw in multicraft, not allowing editing based on a narrow whitelist of file extensions. I would suggest reaching out to your host asking them to enable editing that extension.

In the short term, is it possible to rename the file to .yml and then back?

**Comment by Aligayah** [comment]
I am the host.

**Comment by CmdrKittens** [comment]
Alright, then update your config for the web editor to allow editing that extension.
