### ISSUE TITLE
Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by NiveryIGN** [drtshock/PlayerVaults#411]
**PLUGIN VERSION**
`[INFO] PlayerVaults version 4.1.10

[INFO] Website: https://www.spigotmc.org/resources/51204/

[INFO] Authors: drtshock, kashike and `CmdrKittens``

**SERVER VERSION**
`[INFO] This server is running CraftBukkit version git-Bukkit-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

[INFO] Checking version, please wait...

[INFO] You are 823 version(s) `behind``

**LOGS**
https://gist.github.com/NiveryIGN/d7b887827d7e51f50edbf084bf1e5624#file-gistfile1-txt

**DETAILS**
Whenever a player clicks anywhere in any of their player vault, I get an error in the console about some player click event. I have just bought this plugin and it is running on a Skyblock server. I do not intend to my craftbukkit to spigot or update it as I want my server to be 1.12.2. I expect it to be fixed as I just spent $10 on a small plugin. Thank you.

**Comment by NiveryIGN** [comment]
It seems it is not only when a player clicks in the player vault but anywhere that is like an inventory.

**Comment by CmdrKittens** [comment]
It looks like this is a bit of code that md_5 didn't merge into his fork of Bukkit until later on. Try running on Spigot (or, preferably, Paper) on 1.12.2 to see if the problem goes away.

**Comment by NiveryIGN** [comment]
I'm scared that if I switch to Spigot/Paper I'll lose plugins.

**Comment by CmdrKittens** [comment]
If anything, plugins should provide *better* functionality on Paper. Plugins that break on Paper are super rare and, often, poorly coded anyway. It's worth a test at least, to see if everything loads fine on it! :)

**Comment by NiveryIGN** [comment]
So even if all my plugins are Spigot/Craftbukkit it should be okay as long as I keep 1.12.2? Along with all the user data and everything? Because I have players who have been playing on the server for a week now and I don't want them to lose everything.

**Comment by CmdrKittens** [comment]
Yep! Paper is meant to be a drop-in replacement. It is, of course, always worth taking backups, but I haven't ever seen someone lose data just from swapping the Paper jar in.

**Comment by NiveryIGN** [comment]
Alright so if I understand, I'm gonna have to switch from Craftbukkit 1.12.2 to Paper 1.12.2. All my plugins and user date will be fine and even if it's not, I'll have a backup. Then the plugins will work and there will be less errors in general because Paper provides a better functionality than Craftbukkit. Is that right ? Just making sure lol.

**Comment by CmdrKittens** [comment]
Yep!

**Comment by NiveryIGN** [comment]
Alright, thank you so much for the quick response :D
