### ISSUE TITLE
PlayerVault completely wiped.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#413]
One of our player's vaults got completely wiped.
First time we ever saw this happen.

Paper 1.15.2 - Build 365
PlayerVaults compiled on: https://github.com/drtshock/PlayerVaults/commit/8cc830eb7e70cf108615c0d5f6bb04e14ce84262

Logs show the following on command: **/pv 1**
https://pastebin.com/uQP6AKgi

Last backup of this vault **(/pv 1)** is:
https://pastebin.com/raw/3PQDfxut

Last backup of this player entire vault file (yes it's massive):
https://pastebin.com/LfSXYLBS

**Comment by CmdrKittens** [comment]
Whoops forgot to close! This was a Paper bug and has since been resolved.
