### ISSUE TITLE
Vault wiped after putting a certain item in

### ISSUE THREAD

**Issue by Querrin** [drtshock/PlayerVaults#414]
### PlayerVaultsX Version
v4.1.11

### Server Version
1.16.1 git-Spigot-4d9262c-dc7c3c6 

### Stack trace
https://pastebin.com/NaH3981C

### Details
The issue is caused by putting a spawner generated by UpgradableSpawners (https://www.spigotmc.org/resources/upgradeable-spawners-minecraft-spawner-plugin-level-spawner-change-entity-type-1-16-support.77717/). 

As you can see above the stacktrace, I had given myself the spawner, opened the vault and put it in. Upon reopening the vault again, the exception was thrown and the player vault was completely wiped.

**Comment by CmdrKittens** [comment]
Hello there! I'm sorry to hear about the trouble you're running into! Since I do not have access to this plugin, can you try testing this on another MC server version as well as testing on Paper 1.16?

**Comment by Querrin** [comment]
Sorry for the late reply, GitHub didn't send me an email. I can test it on another spigot server but I will not be using paper, as some of the plugins I use do not work with it (for a good reason).

**Comment by CmdrKittens** [comment]
Thanks for being willing to look into it!

I am not going to try convincing you to try Paper, but I am curious. Could elaborate on the plugins not working with it and what you mean by "for a good reason" comment?

**Comment by Querrin** [comment]
Tried with spigot on localhost, I can replicate the issue. I feel no need to post the trace again as it is the same thing.

For the why I don't use paper, it's because of a custom world generator. They tried to add support for paper but apparently the chunk loading on it is very unstable, combined with the developers not seeming to care. This does not mean I hate paper, in fact I would prefer to use it, but if issues like that exist, I won't be switching.

I don't mean to be rude but for the better of both of us, let's end the conversation about Paper/Spigot debate as most of the time it ends in a meaningless argument spiraling into the depths of a black hole, where people actually start to insult others because of their different preference.

**Comment by Querrin** [comment]
I tried it with paper 1.16.1 build 73 as you requested, the issue is still present.

**Comment by CmdrKittens** [comment]
Can you send a user's vault file that will fail to load?

**Comment by Querrin** [comment]
No problem.

Before putting item inside (an empty vault)
https://pastebin.com/WxaEJYR2

After putting the item inside and closing the vault
https://pastebin.com/WQczaQzX

After exception
https://pastebin.com/zq5PmVSA

**Comment by Querrin** [comment]
Any info?

**Comment by ZEROOblivious** [comment]
My Server is having the same issues with Shulker Boxes. 
If you place a Shulker inside it completely wipes the PV.

**Comment by mbax** [comment]
Hah, look at me not closing issues after they're resolved. This is fixed as of 4.2.0.
