### ISSUE TITLE
Confirmation when buying a new PV.

### ISSUE THREAD

**Issue by BoBsmil3Y** [drtshock/PlayerVaults#416]
Hey 

### Idea
Have an option to confirm if they really want to create a new PV. 
Can be really cool to have when you use economics options where you charge them from buying a new one. I set it pretty high on price, and if they missclick and open a PV they don't actually own, they pay for it without being "agree" for that. Miss take can be expensive :x 

### Details
On config : adding if we want to add a "protection" before buying a PV. So you can disabled that.
On traduction file : adding one line for the syntaxe.

Can be very cool 👍 
Have a great day all.

**Comment by mbax** [comment]
Purchasing has been revamped in 5.0 and therefore this issue is substantially lessened
