### ISSUE TITLE
PV's still being reset at random times

### ISSUE THREAD

**Issue by ItsDed** [drtshock/PlayerVaults#417]
### PlayerVaultsX Version
PlayerVaults version 4.1.15

### Server Version
This server is running Purpur version git-Purpur-747 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

### Logs
Can provide if asked

### Details
Still having issues with PVs getting reset randomly. I haven't been able to reproduce this in any manner, and it seems to primarily happen to staff members.

It hasn't happened in about 2 weeks, so I don't think the log files will have any useful information. But I can provide if needed.

This isn't a huge deal because I'm taking daily backups to combat this issue. I just thought I would mention that it's still present on my server.

**Comment by mbax** [comment]
Resolved as of 4.2.0
