### ISSUE TITLE
World Disable Option

### ISSUE THREAD

**Issue by AccioAce** [drtshock/PlayerVaults#418]
### Idea
World Disable - Ability to disable players from using vaults in certain worlds.

### Details
My idea is to have a world disable option in the configuration so that we can disable players from using there vaults in certain worlds.

I figure out a way where players can transfer items from creative mode to survival mode.

Example: Let say if someone goes into a different world using multiverse (world that have creative mode set), they can go into there vault and add items from creative mode and then go back to survival to open vault to get the items. I would like to find ways to prevent that from happening.

**Comment by mbax** [comment]
This can be done using a permissions plugin.
