### ISSUE TITLE
MySQL and BungeeCord Support

### ISSUE THREAD

**Issue by orkun1675** [drtshock/PlayerVaults#42]
Can you add mysql support and fast syncing so we can use it to transfer inventories in bungeecord setup servers? Other plugins out their are all laggy. I want to continue with this one if possible.

Thank you!

**Comment by drtshock** [comment]
This isn't high priority but might be revisited.

**Comment by Punkred** [comment]
would like to see some mysql support aswell.

**Comment by MinecraftAdmin** [comment]
Ditto on MySQL support! It will give this plugin a lot of utility!
