### ISSUE TITLE
Bug that totally clears PlayerVaults.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#421]
Paper 1.16.3 Build 240
PlayerVaultsX 4.1.15 built on https://github.com/drtshock/PlayerVaults/commit/8b65db8fc1b6e36c155774ed4f1b2fc75640bdde

Original report:
https://ecocitycraft.com/forum/threads/bug-report-player-fault-item-deletion.204301/

Video of reproduction:
https://youtu.be/YiSDLThKh8E

Verified this several times.
Seems to be quite a funky one. Let me know if you need more information.

(Powertools set by Essentials.)
(/anvil and other interfaces all by different plugins, basically any interface powertool causes this.)

**Comment by mbax** [comment]
Well that's ... special.

I have a pretty good guess at what's causing it, and will work on creating a simple reproducible case to test against.

**Comment by mbax** [comment]
Finally had the time to try. Set up a plugin to simply pop a new inventory and it does successfully save first before popping the new inventory up. Any way I could see the relevant power tool code? (Can do it privately, for example over Discord private message)

**Comment by andrewkm** [comment]
This was all our fault, we we're firing the open event.
Derp. <3 Thanks for the quick responses mbax 👍
