### ISSUE TITLE
Allow Players to buy additional vaults in game with eco monies

### ISSUE THREAD

**Issue by ChitterChatter** [drtshock/PlayerVaults#422]
### Idea
Allow Players to buy additional vaults in game with eco monies

### Details
Using some type of eco system, supporting essentials and CMI and whatever else there is, allowing players in game to purchase additional vaults using in game money.

**Comment by Roos-Skywalker** [comment]
Yes, so much yes.
A workaround for now is to sell the permission node playervaults.amount.# with the amount you want for the currency you want.

**Comment by mbax** [comment]
Planned for 5.x

**Comment by mbax** [comment]
Purchasing implemented in 5.0, currently in alpha testing.
