### ISSUE TITLE
[Feature Request] Ability to have a "next page" in vault menu and sort vault option

### ISSUE THREAD

**Issue by ChitterChatter** [drtshock/PlayerVaults#424]
### Idea
Hi there, I was wondering if it possible to have an option in the vault gui where you can click to the next page, as well as sort the current open vault? 

I am sure you might have been asked for these features, but I couldn't see a ticket about it so I thought I would ask anyways.

What about even options to store xp or money as well?

### Details
Umm, there used to be a vault plugin that did this that has since gone inactive.  Attached is a screenshot of that other plugin, as you can see there is a sort feature. Players were able to name their vaults and even assign icons to the vault names. 

Is all this possible?

![SortVault](https://user-images.githubusercontent.com/28234726/104702172-78807880-56ca-11eb-8846-1da62d7c0139.PNG)

**Comment by mbax** [comment]
Currently we are working on rewriting a bunch of internals to support a more flexible set of options for displaying vaults, including naming vaults, defining custom sizes per-vault, and (relevantly) optionally supporting next/prev buttons for going between them. :)

As for sorting, that's an interesting idea. Don't think I've seen that yet! :)

**Comment by mbax** [comment]
Next/Prev buttons implemented in 5.0, currently in alpha testing. Sorting added for consideration to the possible feature board. Closing issue here, though, because this is no longer the primary repo.
