### ISSUE TITLE
error show when Admin open not exist player vaults

### ISSUE THREAD

**Issue by netherstar** [drtshock/PlayerVaults#425]
PlayerVaults version 4.1.16
Server: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

This error show when Admin open not exist player vaults (example player has only 1 vault but admin open /pv Player 3)
https://gist.github.com/netherstar/47b4a4859a90daf9d4248b4e541b5738

**Comment by mbax** [comment]
This is potentially fixed in 4.2.x, closing pending further info.
