### ISSUE TITLE
I need op

### ISSUE THREAD

**Issue by TermedPolecat40** [drtshock/PlayerVaults#428]
<!-- PlayerVaultsX Issue Template
Don't put anything inside this block, as it won't be included in the issue.

If you have a question about PlayerVaultsX, it may be more useful to join our
Discord server: https://discord.gg/F7gexAQ. Check the wiki, https://github.com/drtshock/PlayerVaults/Wiki,
as well to make sure this has a fix. Also check to see if this issue has
already been reported.

1.  Fill out the template, running the commands either in the console or 
    as a player. Don't simply put "latest" or we will ignore it.
2.  When linking files, do not attach them to the post! Paste them on 
    https://gist.github.com/, then paste a link to them in the relevant parts
    of the template. Avoid using Hastebin or Pastebin, as files are deleted
    after a period of time.
3.  If you are reporting an issue with lag, please include a timings report.
4.  If you are reporting an issue with messages or in-game behaviour, please
    include screenshots detailing the problem.
5.  Include a description and any other details that may be helpful under
    "Details:"

### Details
*Please explain the problem.*
When me and my friends do PV 1 it says you need OP￼￼ what do I do

**Comment by mbax** [comment]
Wat
