### ISSUE TITLE
Admin issue when opening an offline player's safe

### ISSUE THREAD

**Issue by mehmet-27** [drtshock/PlayerVaults#433]
I gave the pv row permissions to the players. For example, the player has 5 lines, but if I open his pv while he is offline, it shows only 2 lines of the player and deletes everything in the other 3 lines.

**Comment by mbax** [comment]
Set the config default max rows back to six, and grant perm nodes to control the number of rows users get. 

I'd like to resolve this properly but I think doing this change fixes it for you.

**Comment by mehmet-27** [comment]
Thanks
