### ISSUE TITLE
Per slot unlocks

### ISSUE THREAD

**Issue by daoshii** [drtshock/PlayerVaults#439]
### Idea
Would be nice to have the ability to unlock slot by slot if that option was enabled. Itd made it easier to be a gold dump if they had to unlock each slot, rather than only a few row unlocks.

### Details
I've seen a few servers utilize this by adding stained glass to the locked slots, you click the next stained glass in line and unlock it for vault currency.

**Comment by mbax** [comment]
Hi, I'm embarrassed that I missed this being opened.

The plan for 5.x is to swap out the current system for granting access to a *type* of vault, which would be defined by how big it is (and what slots are available). It would theoretically be possible to, in this new system, grant access to a vault that stores one more item than the current one, and revoke the old one, and have it dump items into the new one. 

But, I can't guarantee that will be how it works out - it's still being written.

**Comment by daoshii** [comment]
Not a problem, appreciate the reply ill look out for that in 5.x!
