### ISSUE TITLE
pv problem

### ISSUE THREAD

**Issue by mrpunky** [drtshock/PlayerVaults#441]
When the players buy VIP, I increase the number of /pv to 2 at once, but as the vips run out, the number of pv slots suddenly drops and all the pages are deleted, can't you set this up more properly?

**Comment by mbax** [comment]
The entire vault gets deleted? That seems odd. Just for confirmation, can you give me your current version of the plugin in use? Double check for me please :)

**Comment by mbax** [comment]
Closing due to no reply.
