### ISSUE TITLE
Offhand Blocked Items

### ISSUE THREAD

**Issue by NotNoison** [drtshock/PlayerVaults#444]
PlayerVaults 4.2.6

This server is running Pufferfish version git-Pufferfish-68 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 629b5b3 on HEAD)
You are running 4 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-66 (MC: 1.18.2)

[latest (3).log](https://github.com/drtshock/PlayerVaults/files/8947379/latest.3.log)

So when you block items through the config of PlayerVaults you can bypass them doing F on the blocked item then F in the PlayerVault.

**Comment by mbax** [comment]
Sorry for missing this, I don't know how I missed the notification!

This will be fixed in the upcoming release. Code works already, just need a few finishing touches.

**Comment by mbax** [comment]
This is now live.
