### ISSUE TITLE
Please update Adventure.

### ISSUE THREAD

**Issue by andrewkm** [drtshock/PlayerVaults#445]
https://github.com/ViaVersion/ViaVersion/issues/3070
Please update Adventure (4.1.2-SNAPSHOT) Dad.

**Comment by mbax** [comment]
I'm sorry, Son. I was out buying milk from the store.

Releasing new version shortly.

**Comment by andrewkm** [comment]
Me and mom waited 6 years...

**Comment by andrewkm** [comment]
@mbax bro push to master or I’ll eat a hamster…

**Comment by mbax** [comment]
@andrewkm I forgot to push while cooking you dinner. Put your pet down!

**Comment by andrewkm** [comment]
Don't temp me @mbax or I'll get banned again from some place I'm not banned from yet. PA: This beer good!!!

**Comment by mbax** [comment]
❤
