### ISSUE TITLE
Item Attributes not saving

### ISSUE THREAD

**Issue by Alexz1008** [drtshock/PlayerVaults#446]
### PlayerVaultsX Version
*Run `/version playervaults` and give us your output.* 
[02:42:59 INFO]: PlayerVaults version 4.2.10
[02:42:59 INFO]: Website: https://www.spigotmc.org/resources/51204/
[02:42:59 INFO]: Authors: drtshock, kashike and mbaxter

### Server Version
[02:43:48 INFO]: This server is running Paper version git-Paper-125 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3f0415b)
You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-111 (MC: 1.19.1)

### Logs
*Give use your logs by going to `logs/latest.log`.*
The logs are enormous and there are no error messages from playervaults, so I won't add it here unless you specifically ask.

### Details
*Please explain the problem.*
I put an item with modded attributes into a player vault (for example, a Netherite Chestplate with Armor +12 and Armor Toughness +10). Upon restarting the server, the item is reverted into the default netherite armor and armor toughness. It seems name and lore and such are retained fine though.

**Comment by mbax** [comment]
To accurately test, can you give me information on how you are creating that custom item? Latest version of this plugin (which you say you have) shouldn't be modifying the item like *that*.

**Comment by Alexz1008** [comment]
After looking for 5 days for a proper reproduce, I have discovered it was user error -_-'. Hope you didn't waste too much time on this.

**Comment by mbax** [comment]
I'm glad you got it resolved! 😄
