### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Zapry** [drtshock/PlayerVaults#449]
### PlayerVaultsX Version
*Run `/version playervaults` and give us your output.* 
3.6.0-bSNAPSHOT

### Server Version
*Run `/version` and give us your output.*
git-Purpur-1982 (MC: 1.19.4)*

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://gist.github.com/Zapry/c0c127f1f135a832de6a76ac1fe2097a

### Details
*Please explain the problem.*
I dont know how it happens, but flag lots of logs

**Comment by mbax** [comment]
`v3.6.0-bSNAPSHOT` is incredibly outdated.
