### ISSUE TITLE
FEAT: Add a possibility to name vaults

### ISSUE THREAD

**Issue by ghost** [drtshock/PlayerVaults#450]
It would be nice if we could name specific vaults so that we can open it using a name instead of a number. For ex. I have 5 vaults and can access them with `/pv <number>`. 

I wish I could do something like `/pvname <number> <name>` after wich I could open a vault with `/pv <name>`.

This will make it easier to organize items in vaults, because instead of remembering in which vault did I put what, I can do `/pv armor` or `/pv food`.

Ofc the command would need a countercommand, so either calling `/pvname` again would rename existing one, or `/pvdelname <number>` would remove the name completely. The named vaults would be still accessible via their numbers, so it's only an addition to the current functionality.

Cheers.

**Comment by mbax** [comment]
Names coming in rewrite 😄

**Comment by triesharder** [comment]
Also requested on #404

**Comment by mbax** [comment]
Now tracking here, for 5.0 https://github.com/KittehDev/PlayerVaultsX/issues/3
