### ISSUE TITLE
Allow player to retrieve items after permission expiration

### ISSUE THREAD

**Issue by SkirmisLTU** [drtshock/PlayerVaults#454]
### Idea
Enable players to retrieve items from vaults they no longer have access to.

### Details
For instance, a player initially possessed the temporary permission `playervaults.amount.2` and actively utilized vault 2. However, after the permission expired, access to the vault and its existing items was revoked. The desired functionality is to implement a feature allowing the player to retrieve items from the expired vault, while preventing the addition of new items. There are a few alternative solutions, such as transferring all items from a vault that the player no longer has access to, to a vault that the player currently has access to (if the vault has available space). This configuration should be customizable in the settings.

**Comment by mbax** [comment]
This is on the requirements-for-launch list for 5.0, which is currently in alpha testing (without this feature at time of writing, but much of the code is there to be hooked into). This is tracked on this issue: https://github.com/KittehDev/PlayerVaultsX/issues/2
