### ISSUE TITLE
Playervaults defaulting back to 1 slot for no reason

### ISSUE THREAD

**Issue by Fuckyoudammit** [drtshock/PlayerVaults#53]
As the titles says. This has happened to a few of my players, they have permission for a 5 slot playervault, yet they do /pv 1 and its only 1 slot. I gave them the ability to use /pv 1 and /pv 2, this worked for awhile but only the /pv 2 would be 5 slots, now their second playervault is defaulting back to a single slot vault. All of the items are there in the UUID folder, there are no error messages anywhere, all other permissions are working fine. Has anybody else had this problem/know a fix for it? Thank you.

Also, I use playervaults as part of my donation system, people can donate for a higger playervault. When enjin runs the command /pex user {name} add playervaults.size.5, or puts them in a group with the permission, it doesn't make their playervault bigger.

**Comment by drtshock** [comment]
Fixed in https://github.com/drtshock/PlayerVaults/commit/ede738019a5798b5ffc7ed4c56fa625ead362321
