### ISSUE TITLE
Add support for block enitity tag

### ISSUE THREAD

**Issue by iaxedu** [drtshock/PlayerVaults#56]
Please add support for block entitiy tag such as silkspawners use: http://dev.bukkit.org/bukkit-plugins/silkspawners/files/41-silk-spawners-v3-6-2-1-5-up-to-1-8/

Also add lores please :)

Thanks

**Comment by DarkPklord3** [comment]
Sorry if this is bumping a dead ticket/thread, but i was just about to submit a ticket with this exact problem. After a server restart or crash, all spawners in players vaults are changed to just monster spawner's and lose the entity. (defaults to pig). Its a problem that i would imagine others are having and i think there should be some sort of fix to it :s

**Comment by drtshock** [comment]
Duplicate of #62 (his ticket has more info). Please comment on there if you're still interested.
