### ISSUE TITLE
Size don't change?

### ISSUE THREAD

**Issue by madtomic** [drtshock/PlayerVaults#58]
Size of chest don't change if user is in a different group with different size.

example.

guest
    - playervaults.amount.1
    - playervaults.size.3

member
    - playervaults.amount.2
    - playervaults.size.6

Player join server, vault 1 is 3 rows, if get promoted to member. now he can have two vaults. but vault 1 is still at 3 rows and vault 2 is at 6. can this be fix?

**Comment by madtomic** [comment]
The only way is to use delete vault 1 and it will reset it to 6 rows. weird bug

**Comment by TheOnlyRealTGS** [comment]
You can fix it by restarting
