### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by LGCMcLovin** [drtshock/PlayerVaults#60]
A couple of suggestions i had for the playervaults plugin.

Search feature by command for example /pv search red - returns any itemstacks in senders playervaults with arg "Red" in item name, displayed in inventory gui 

Using 1.6.4 minecraft and the most recently listed version of playervaults for 1.6.4 there is a "Bug" if you will in how the itemstack data is stored in player vaults, for example, putting a Tinkers construct pick of any sort into a player vault will default the pick to Wood, A backpack or other item of this sort that stores items inside of it lose any items stored within it, items that hold charges, lose charges in playervaults.

These features would increase compatibility with modded servers, add a searchable item storage system to vanilla, and allow some modded server owners to rid their servers of some of the tile entity heavy item storage mods in modpacks like attack of the bteam.

**Comment by LGCMcLovin** [comment]
Thank you for your time, fingers crossed i really look forward to these features

**Comment by drtshock** [comment]
What's a tinkers construct pick? If you're using a mod, the mod needs to correctly add the new items with Bukkit's API for PV to be able to serialize the items. If done correctly, PV will have no issues with any modded items.

As for your search feature, that could possibly be added.

**Comment by drtshock** [comment]
After looking into this more, I just don't think it's something we'll be adding. Searching tons of text files just doesn't seem like the best idea for this plugin as I don't like to add many if any features outside the core plugin.
