### ISSUE TITLE
Mob Spawners in Vaults Become Pigs After Restart

### ISSUE THREAD

**Issue by ArmanA145** [drtshock/PlayerVaults#62]
Say I give myself a spider spawner, using:

/give Arman mob_spawner 1 0 {BlockEntityTag:{EntityId:Spider}}

So, this will give me a fully functional spider spawner. Now, if I store this spawner inside a PlayerVault, and take it out, it's still a spider spawner. 

If I store it inside a PlayerVault, restart the server, and take it out, it's a pig spawner. This happens with all mob spawners!

Spigot Version: http://prntscr.com/6c1cb1
PlayerVaults Versin: Build 160 from https://ci.drtshock.net/job/PlayerVaults/lastBuild/
Errors: None!

I understand the plugins development is halted, but I would really appreciate if you could try to fix this issue!

Thanks for your consideration,
Arman

**Comment by Shmeeb** [comment]
This also happens to me.

**Comment by drtshock** [comment]
This plugin currently isn't being maintained.

**Comment by MoeXIV** [comment]
Ouch!

**Comment by drtshock** [comment]
Can you paste the player's vault file (<uuid>.yml) before the restart with the item in there, again after the restart with the spawner in the vault still before touching it, and finally a third copy of the file after taking the spawner out and putting it back in after a restart.

**Comment by drtshock** [comment]
Would still love the above information ^^

**Comment by drtshock** [comment]
Changing this to enhancement as it would require me to switch from only bukkit serialization to saving NBT tags and breaking with minecraft updates, which I don't want to do :(

**Comment by ArmanA145** [comment]
I'm sorry for the late reply!

Before (working spider spawner in vault): http://pastebin.com/vQxxwq3K

After (vault unopened): http://pastebin.com/kQKnbbf2

After (moved the spawner, it had turned to pig): http://pastebin.com/BjYqeeAV 

I understand completely why you don't want to work on this, you've got many important resources on Spigot you're actually getting paid for. But, it'd be a huge favor and i'm sure many people would be thankful. Hell, if you were to release PlayerVaults as a premium resource and continue updating it, i'd totally purchase it.

**Comment by drtshock** [comment]
Yeah I'm thinking of releasing it as a paid resource if I can get this 'fixed' as it's pretty big. Only issue is that it'll make the plugin break between versions :c

**Comment by ArmanA145** [comment]
Thanks, I look forward to seeing PlayerVaults actively updated again, if that is what you decide!

**Comment by RAZERMC** [comment]
Can you atleast please put a black list setting on the config, our server uses the silkspawner plugin and when ever they put it on pv even without restarting it becomes a pig spawner. Some of my players accidentally put their blaze spawner in pv 1 they know it will turn into pig spawner so they auctioned it and now the player who bought it got the fake spawner. We really appreciate the work you have done on this plugin hope this plugin gets up again. thanks again.

**Comment by RAZERMC** [comment]
off the thread topic your sign permission still malfunctioned after server restart we found a work around with another plugin but it would be convenient if the sign permission can be fixed to avoid using another plugin to lessen the server load

**Comment by vemacs** [comment]
Does this still happen in the latest 1.8.3 versions and 1.8.7? Spigot moved spawner data to BlockStateMeta which should be serialized.
