### ISSUE TITLE
PlayerVault Sign Suggestion - Buy Sign

### ISSUE THREAD

**Issue by NotoriousV2** [drtshock/PlayerVaults#66]
Could you perhaps make purchasing vaults and using them via signs separate signs? Currently (as I'm sure you know), when a player clicks a sign, the vault is purchased for them and then opened. An issue I'm having (and can't think of a way to fix) is that new players will either miss-click, or click around for whatever reason and accidentally spend the set amount on the vault even if they're not wanting to.

A plugin that comes to mind that uses this sort of feature is ChestKeeper. There would be a buy sign, and an open sign. Even after updating ChestKeeper to support UUIDs, the plugin still doesn't save items properly, eats items, dupes items etc... so I've been basically forced to switch over to PlayerVaults as it's really the only good option currently.

**Comment by drtshock** [comment]
What would you want the syntax of this to be? And then if they try opening the vault before they've purchased it, would you want it to purchase or just not open?

**Comment by NotoriousV2** [comment]
I'm not sure. Perhaps "pvbsign <vault#>" and have the person right click a sign-post to set that specific sign as a vault buy sign sort of like the set vault sign works.

If they try to open a vault that they don't own, it just wouldn't open -- perhaps sending them a message that they don't own this vault, and they must purchase it from the buy vault sign.

**Comment by NotoriousV2** [comment]
On top of this, would a ChestKeeper converter be possible to implement? Will be moving over to this if/once this buy-sign is implemented.

**Comment by drtshock** [comment]
I'll have to do a bit of refactoring for the buying. I've been busy with another project so haven't had time to revisit this. I'll look at adding it early next week.

As far as a converter, if you can make a new ticket and include sample files so I know how they store data and a link to their github repo. I can take a look.

**Comment by NotoriousV2** [comment]
Any update on this, or have you been busy with the other project? I'm not trying to rush anything; just completely curious!
