### ISSUE TITLE
enchantment

### ISSUE THREAD

**Issue by theshadyonehd** [drtshock/PlayerVaults#67]
Hello, Is there a way to implement players not placing or taking a item or limited the amount per chest. I want this feature as I do not want players to take spawners onto the new server.
Thank you.

**Comment by drtshock** [comment]
what ;o

**Comment by theshadyonehd** [comment]
what bit dont you understand?

**Comment by drtshock** [comment]
The entire OP doesn't make any sense.

**Comment by CassandraWipf** [comment]
I believe what they are trying to say is would it be possible to restrict certain items from being placed in player vaults, ie. not being able to place a spawner in a player vault.

**Comment by drtshock** [comment]
That's something that I don't see being added.
