### ISSUE TITLE
duplication glitch

### ISSUE THREAD

**Issue by theshadyonehd** [drtshock/PlayerVaults#68]
if you use command '/pv <player> <#>' it replaces the other players player vault to your  vault.

**Comment by drtshock** [comment]
what other player's?

**Comment by theshadyonehd** [comment]
so if i open player 'jimmy' player vault it will will replace all of my content in my player vault with jimmy's player vault content.

**Comment by drtshock** [comment]
Please provide step by step way of reproducing this.

**Comment by theshadyonehd** [comment]
1. use command '/pv 1 <player>' on other player (maybe both need to be OP/admin perms)
2. user command '/pv 1'
3. see items have been copied to your vault

**Comment by CassandraWipf** [comment]
I am having this issue as well, I check a players vault with '/pv <name> 1' and it copies their vault to mine, so when I do '/pv 1' my vault has the same items as theirs.

**Comment by drtshock** [comment]
Ok thanks for the semi clear description. Was very easy to find once I knew what to look for (:
