### ISSUE TITLE
ChestKeeper Converter

### ISSUE THREAD

**Issue by NotoriousV2** [drtshock/PlayerVaults#69]
Could a ChestKeeper Converter be implemented? :)

Original ChestKeeper repo: https://github.com/jjkoletar/ChestKeeper
UUID support repo (bit bugged): https://github.com/mattgd/ChestKeeper

Sample file of saving: http://pastebin.com/yyQEfRW0

I will provide more information if I missed something.

**Comment by drtshock** [comment]
Which version are you using? The mattgd or the jjkoletar one?

**Comment by drtshock** [comment]
Actually, I can see the answer to that by opening the file. Can you please paste an unedited file from whichever version you're using? Also give me the file name and folder structure.

**Comment by NotoriousV2** [comment]
Zipped up the ChestKeeper folder, which includes everything including a sample saved inventory with a few items. Download link to dropbox: https://www.dropbox.com/s/m553hhi9efcto7v/ChestKeeper.rar?dl=0

The saving uses an edited version of CardboardBox (https://bukkit.org/threads/cardboard-serializable-itemstack-with-enchantments.75768/)

**Comment by Punkred** [comment]
If you can. could you also make it possible to convert chests from virtualpack?
