### ISSUE TITLE
PlayerVaults Storage

### ISSUE THREAD

**Issue by stefan15ist** [drtshock/PlayerVaults#70]
PlayerVaults doesn't support banners in the vault.
I'm using verson 3.5.2
and this is the error:
http://prntscr.com/76r8q3

**Comment by drtshock** [comment]
Can you update to 3.5.3 and tell me if you still have this issue? If so, please paste the player's yml file.
https://ci.drtshock.net/job/PlayerVaults/169/

**Comment by stefan15ist** [comment]
I still get an error:
http://prntscr.com/76s308
here is the file:
http://hastebin.com/gufeqeneku.md (line 19)

**Comment by stefan15ist** [comment]
btw, did you change permissions, they don't seem to be able to use the vaults

**Comment by drtshock** [comment]
Yeah I updated them on the bukkitdev page though.

**Comment by stefan15ist** [comment]
playervaults.amount.# ? I have playervaults.amount.3, and they can't use any

**Comment by stefan15ist** [comment]
in the version 3.5.1 permissions were fine, 3.5.2, and 3.5.3 something is wrong.

**Comment by drtshock** [comment]
What version of spigot is this?

**Comment by drtshock** [comment]
Also, are you able to get this every time you put a banner in a vault?

**Comment by kashike** [comment]
@stefan15ist Is this still an issue?

**Comment by stefan15ist** [comment]
I don't even know what you are talking about anymore

Date: Mon, 8 Jun 2015 12:27:56 -0700
