### ISSUE TITLE
InventoryClickEvent error on Build 172

### ISSUE THREAD

**Issue by iaxedu** [drtshock/PlayerVaults#76]
Spigot: git-Spigot-b3c0272-7723b90 (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

Error:
http://pastebin.com/U4ADpMmD

**Comment by SmallSansSerif** [comment]
same for me

**Comment by drtshock** [comment]
Should be fixed here https://github.com/drtshock/PlayerVaults/compare/c2fa317e169c...a5ed2b1f4dc2
