### ISSUE TITLE
/pv <player> # changes to your  /pv

### ISSUE THREAD

**Issue by z1haze** [drtshock/PlayerVaults#79]
As an admin if you want to look at another players pv by using /pv <player> <vault-number> after you are finished and try to acess your pv or another player's pv it remains  the first pv that you looked at. please fix. Im running your latest version on bukkit and on spigot 1.8.7

**Comment by drtshock** [comment]
Let me know if you still have this issue on build 174

**Comment by z1haze** [comment]
where is your ci? I dont see dev builds on the bukkit page

**Comment by drtshock** [comment]
https://ci.drtshock.net/job/PlayerVaults/

**Comment by z1haze** [comment]
hey, it looks good man, thanks alot.

**Comment by drtshock** [comment]
Fixed your issues?

**Comment by DroidVengeance** [comment]
Had the same issue, Updated to the latest build and works flawlessly. Thanks!
