### ISSUE TITLE
[Request] Compatible with Multiverse-inventories

### ISSUE THREAD

**Issue by conetopia** [drtshock/PlayerVaults#86]
Hello, im running a 1.8.7 spigot rpg server.
I'm trying to figure out how to make player vaults compatible with Multiverse-Inventories.
Example, when i leave spawn area to go to Islandworld(skyblock) or creative plots.
Based on the multiverse plugin, my inventory changes.
However... the vaults stay the same.

Any ideas? Fixes?
Future requested idea possible?

**Comment by drtshock** [comment]
Not really within the scope of this plugin. You can just revoke permissions in certain worlds if you don't want a player to access any vaults.
