### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by TheExceed** [drtshock/PlayerVaults#90]
If you keep your playervault open and remove everything before the server restarts while keeping the playervault inventory open as it restarts, they log on and still have everything in the pv and inventory.

**Comment by drtshock** [comment]
Your server isn't shutting down correctly then. We handle open vaults on shutdown and player kick.

**Comment by TheExceed** [comment]
My server is shut down via multicrafts scheduled tasks feature.

**Comment by TheExceed** [comment]
An suggestion on fixing this?

**Comment by TheExceed** [comment]
Hello?

**Comment by drtshock** [comment]
Your server isn't shutting down correctly.
