### ISSUE TITLE
Disabling /pv in some worlds

### ISSUE THREAD

**Issue by 151baccardi** [drtshock/PlayerVaults#94]
I give players access /pv as a donation.
I use groupmanager and want to deny players to use /pv in creative world , PVP wordls and faction world. I added 	the permission - -playervaults.commands.use to those worlds permission nodes in groups but player can still use /pv .

How do I disable the command if the user has playervaults.commands.use in their user permissions list ?

Thanks

Perhaps in the config you could add worlds where /pv doesn't work ?! Or maybe there's another workaround. Please help as people fill their chests in creative world and then sell them in main world . YIKES

Disabled Worlds:
Creative
PVP
Factions

**Comment by CHarrisMedia** [comment]
Use PEX and negate the permission from the player in the specific world.

**Comment by 151baccardi** [comment]
We use groupmanger.
We have 22 Worlds.
We are not re-writing 172 permission groups with hundreds of entries each in PEX. Besides, we have 27K users in our users.yml which would also need to be re-written for PEX. This is not a solution.

Negating the permission in groupmanagers 'groups.yml' file is over-ridden by by the permissions given in the users.yml file. Can't you simply add a section in the config that lists the worlds where /pv will work/not work ?

**Comment by PgBiel** [comment]
You can give PerWorldPlugins a try.

**Comment by drtshock** [comment]
Make sure you are properly negating the permission in the world. Try asking groupmanager for support.
