### ISSUE TITLE
blocked-items glitch

### ISSUE THREAD

**Issue by GJplaysmc1500** [drtshock/PlayerVaults#96]
blocked-items:
- MOB_SPAWNER
  that's in my config.  So, the player cannot hold shift and click it to put it in the player vault.  However, they can click the item, and drag it manually into the gui.  Then once its in there, it cant be taken out...
  Hopefully this can be fixed asap, as there is no support for spawners.

**Comment by drtshock** [comment]
Which version are you on? The code in that method has changed a bit lately. And I'm assuming you can reproduce this with any item?

**Comment by drtshock** [comment]
Mentioned in #93.
