### ISSUE TITLE
PlayerVaults Suggestion - Predefined vaults

### ISSUE THREAD

**Issue by Speedlegs** [drtshock/PlayerVaults#97]
Hello,

Our server would like to use your PlayerVaults plugin but we have one problem.
I would like to set-up vaults in the config of a size ( eg. 9,18,27,...) and give players perm to use that vault. 
They then would have a vault of that size. 
This can be very useful for selling a certain type and size of vault.

As for perms i thought of playervaults.vault.[name put in config].

I hope this is kinda possible and maybe interesting to add.

Thanks in advance.
Speedlegs_

**Comment by drtshock** [comment]
Did you actually read the project page? You can configure the size and amount.
